"""Extended lab commands — Part 3: Discovery (all read-only)."""
from .ext_helper import c

PART = {
    "T1016.001": [c("windows", "powershell -NoProfile -Command \"(Invoke-WebRequest https://ifconfig.me/ip -UseBasicParsing).Content\"",
                    "Reads the host's external IP (internet-connection discovery).")],
    "T1016.002": [c("windows", "netsh wlan show networks mode=bssid", "Wi-Fi network discovery (read-only)."),
                  c("linux", "nmcli -t -f SSID dev wifi 2>/dev/null | head")],
    "T1069": [c("windows", "net localgroup & net group /domain 2>nul", "Permission-groups discovery (read-only).")],
    "T1069.003": [c("cloud", "az role assignment list --all -o table 2>nul || aws iam list-groups", "Cloud groups discovery (read-only; requires cloud CLI auth).")],
    "T1087": [c("windows", "net user & net user /domain 2>nul", "Account discovery (read-only).")],
    "T1087.004": [c("cloud", "az ad user list -o table 2>nul || aws iam list-users", "Cloud account discovery (read-only; requires cloud CLI auth).")],
    "T1217": [c("windows", "dir /s /b \"%LocalAppData%\\Google\\Chrome\\User Data\\Default\\Bookmarks\" 2>nul & echo AF browser-info discovery (read-only)",
                "Locates browser bookmark store (browser-information discovery; read-only).")],
    "T1482": [c("windows", "nltest /domain_trusts 2>nul & echo AF domain-trust discovery (read-only)",
                "Domain-trust discovery (read-only).")],
    "T1518.002": [c("windows", "powershell -NoProfile -Command \"Get-Service|? {$_.Name -match 'veeam|backup|acronis|commvault|shadowprotect'}|Select Name,Status\"",
                    "Backup-software discovery (read-only).")],
    "T1526": [c("cloud", "az resource list -o table 2>nul || aws resourcegroupstaggingapi get-resources", "Cloud service discovery (read-only; requires cloud CLI auth).")],
    "T1538": [c("cloud", "az portal --help 2>nul & echo AF cloud-service-dashboard proxy - open the portal read-only in a browser",
                "Cloud dashboard proxy (read-only).")],
    "T1580": [c("cloud", "az vm list -o table 2>nul || aws ec2 describe-instances --output table", "Cloud infrastructure discovery (read-only; requires cloud CLI auth).")],
    "T1613": [c("other", "docker ps 2>/dev/null; kubectl get pods 2>/dev/null; echo AF container/resource discovery (read-only)",
                "Container & resource discovery (read-only).")],
    "T1614.001": [c("windows", "powershell -NoProfile -Command \"Get-WinSystemLocale|Select Name,DisplayName\"",
                    "System-language discovery (read-only).")],
    "T1615": [c("windows", "gpresult /r 2>nul & echo AF group-policy discovery (read-only)",
                "Group-policy discovery (read-only).")],
    "T1619": [c("cloud", "aws s3 ls 2>nul || az storage blob list --help 2>nul & echo AF cloud-storage-object discovery",
                "Cloud storage-object discovery (read-only; requires cloud CLI auth).")],
    "T1652": [c("windows", "driverquery /v 2>nul | more", "Device-driver discovery (read-only).")],
    "T1654": [c("windows", "wevtutil qe System /c:3 /rd:true /f:text 2>nul", "Log enumeration (reads a few events; read-only)."),
              c("linux", "journalctl -n 5 --no-pager 2>/dev/null || tail -n 5 /var/log/syslog 2>/dev/null")],
    "T1673": [c("windows", "powershell -NoProfile -Command \"Get-CimInstance Win32_ComputerSystem|Select Model; Get-Service *vmtools*,*vmicheartbeat* -EA SilentlyContinue|Select Name\"",
                "Virtual-machine discovery (read-only).")],
    "T1680": [c("windows", "wmic logicaldisk get deviceid,volumename,size /format:list 2>nul",
                "Local-storage discovery (read-only).")],
}
