"""Extended lab commands — Part 2: Exfiltration + Impact (destructive => read-only proxies)."""
from .ext_helper import LOOPBACK_DNS, LOOPBACK_PING, c, loopback_tcp

PART = {
    # ---- Exfiltration ----
    "T1020": [c("windows", "dir /s /b %USERPROFILE%\\*.docx 2>nul | more & echo AF automated-exfil proxy - nothing sent",
                "Read-only auto-collection listing (automated-exfiltration proxy; no upload).")],
    "T1029": [c("windows", "powershell -NoProfile -Command \"$t=(Get-Date).AddMinutes(1); \\\"scheduled window: $t\\\"\"",
                "Prints a future transfer window locally (scheduled-transfer proxy; nothing sent).")],
    "T1048.002": [loopback_tcp("Loopback-only asymmetric-encrypted non-C2 exfil proxy. No data is sent.")],
    "T1048.003": [c("windows", f"{LOOPBACK_DNS} & echo AF unencrypted-non-C2 exfil proxy - no data sent",
                    "Loopback DNS lookup (unencrypted non-C2 exfil proxy).")],
    "T1052.001": [c("windows", "powershell -NoProfile -Command \"Get-Volume|? DriveType -eq 'Removable'|Select DriveLetter,FileSystemLabel\"",
                    "Enumerates removable drives (exfil-over-USB proxy; nothing copied).")],
    "T1537": [c("windows", f"{LOOPBACK_DNS} & echo AF transfer-to-cloud-account proxy — no upload",
                "Loopback DNS lookup (transfer-to-cloud-account proxy; no upload).")],
    "T1567": [c("windows", f"{LOOPBACK_DNS} & echo AF exfil-over-web-service proxy — no upload",
                "Loopback DNS lookup (exfil-over-web-service proxy; no upload).")],
    "T1567.004": [loopback_tcp("Loopback-only webhook-exfil proxy. No data is posted.")],

    # ---- Impact (all read-only / echo proxies — nothing is destroyed) ----
    "T1485": [c("windows", "echo AF > %TEMP%\\af_destroy.txt & del %TEMP%\\af_destroy.txt & echo AF data-destruction proxy - only a temp file touched",
                "Creates+deletes ONE temp file (data-destruction proxy; no real data touched).")],
    "T1495": [c("windows", "wmic bios get manufacturer,version /format:list & echo AF firmware-corruption proxy (read-only)",
                "Read-only BIOS query (firmware-corruption proxy; firmware untouched).")],
    "T1496.001": [c("windows", "powershell -NoProfile -Command \"(Get-CimInstance Win32_Processor).LoadPercentage\"",
                    "Reads CPU load once (compute-hijacking/cryptomining proxy; no mining).")],
    "T1498": [c("windows", f"{LOOPBACK_PING} & echo AF network-DoS proxy - one lab packet only",
                "One loopback ping (network-DoS proxy; no flooding).")],
    "T1499": [loopback_tcp("Loopback-only endpoint-DoS proxy. No flooding.")],
    "T1531": [c("windows", "net user %USERNAME% & echo AF account-access-removal proxy (read-only, nothing disabled)",
                "Read-only account inspection (account-access-removal proxy).")],
    "T1561.001": [c("windows", "wmic diskdrive get model,size /format:list & echo AF disk-content-wipe proxy (read-only)",
                    "Read-only disk enumeration (disk-content-wipe proxy; nothing wiped).")],
    "T1561.002": [c("windows", "wmic partition get name,size /format:list & echo AF disk-structure-wipe proxy (read-only)",
                    "Read-only partition enumeration (disk-structure-wipe proxy; MBR/GPT untouched).")],
    "T1565": [c("windows", "echo original > %TEMP%\\af_data.txt & echo modified > %TEMP%\\af_data.txt & type %TEMP%\\af_data.txt & del %TEMP%\\af_data.txt",
                "Rewrites ONE temp file (data-manipulation proxy).")],
    "T1565.001": [c("windows", "echo v1 > %TEMP%\\af_stored.txt & echo v2 > %TEMP%\\af_stored.txt & del %TEMP%\\af_stored.txt",
                    "Modifies a temp file at rest (stored-data-manipulation proxy).", "del %TEMP%\\af_stored.txt 2>nul")],
    "T1565.002": [c("windows", "powershell -NoProfile -Command \"'lab payload' -replace 'lab','MODIFIED'\"",
                    "In-memory string rewrite (transmitted-data-manipulation proxy; nothing on the wire).")],
    "T1565.003": [c("windows", "powershell -NoProfile -Command \"$x=1; $x=2; \\\"runtime value now $x\\\"\"",
                    "Rewrites a runtime variable (runtime-data-manipulation proxy).")],
    "T1657": [c("windows", "cmd.exe /c \"echo AF financial-theft proxy - no transaction performed\"",
                "Bounded lab simulation only — no financial action is taken.")],
    "T1667": [c("windows", "cmd.exe /c \"echo AF email-bombing proxy - no email sent\"",
                "Bounded lab simulation only — no email is sent.")],
}
