"""Extended lab commands — Part 7: Defense Evasion — indicator removal, impairment, hidden artifacts."""
from .ext_helper import c

PART = {
    # ---- Indicator removal (read/echo only — nothing is actually cleared) ----
    "T1070": [c("windows", "echo AF > %TEMP%\\af_ind.txt & del %TEMP%\\af_ind.txt & echo AF indicator-removal proxy (temp file only)",
                "Deletes a temp artifact only (indicator-removal proxy).")],
    "T1070.003": [c("windows", "doskey /history & echo AF clear-command-history proxy (view only, not cleared)",
                    "Views command history (read-only)."),
                  c("linux", "history | tail & echo 'AF clear-command-history proxy (view only)'")],
    "T1070.005": [c("windows", "net use & echo AF network-share-connection-removal proxy (list only, nothing removed)",
                    "Lists share connections (read-only).")],
    "T1070.006": [c("windows", "powershell -NoProfile -Command \"(Get-Item $env:WINDIR\\win.ini).LastWriteTime\"",
                    "Reads a file timestamp (timestomp proxy; nothing modified).")],
    "T1070.007": [c("windows", "netsh interface show interface & echo AF clear-network-history proxy (read-only)",
                    "Reads network interface config (read-only).")],
    "T1070.008": [c("windows", "cmd.exe /c \"echo AF clear-mailbox-data proxy - no mailbox modified\"",
                    "Placeholder only — no mailbox data is cleared.")],
    # ---- Subvert trust controls ----
    "T1553": [c("windows", "powershell -NoProfile -Command \"Get-ChildItem Cert:\\CurrentUser\\Root|Select -First 3 Subject\"",
                "Reads trusted-root certs (subvert-trust-controls proxy; read-only).")],
    "T1553.005": [c("windows", "powershell -NoProfile -Command \"Get-Item $env:WINDIR\\win.ini -Stream Zone.Identifier -EA SilentlyContinue; 'mark-of-the-web read (proxy)'\"",
                    "Reads the MOTW alternate data stream (read-only; nothing bypassed).")],
    "T1553.006": [c("windows", "powershell -NoProfile -Command \"Get-CimInstance Win32_OperatingSystem|Select Caption; 'code-signing-policy proxy (read-only)'\"",
                    "Read-only proxy for code-signing-policy modification.")],
    # ---- Defense impairment (read-only; nothing disabled) ----
    "T1685": [c("windows", "sc.exe query windefend & echo AF disable-or-modify-tools proxy (read-only, nothing disabled)",
                "Queries the security tool service (read-only).")],
    "T1685.001": [c("windows", "wevtutil gl Security | more & echo AF disable/modify-Windows-Event-Log proxy (read config only)",
                    "Reads event-log config (read-only; logging not disabled).")],
    "T1685.002": [c("cloud", "az monitor diagnostic-settings list --help 2>nul & echo AF disable/modify-cloud-log proxy (read-only)",
                    "Read-only cloud-logging proxy (nothing disabled).")],
    "T1685.005": [c("windows", "wevtutil qe Security /c:1 /f:text 2>nul & echo AF clear-Windows-Event-Logs proxy (read one event, not cleared)",
                    "Reads one event (read-only; logs not cleared).")],
    "T1685.006": [c("linux", "tail -n 3 /var/log/syslog 2>/dev/null; echo 'AF clear-Linux/Mac-logs proxy (read only, not cleared)'",
                    "Reads a few log lines (read-only; logs not cleared).")],
    "T1686": [c("windows", "netsh advfirewall show allprofiles state & echo AF disable-system-firewall proxy (read-only)",
                "Reads firewall state (read-only; firewall not modified).")],
    "T1686.002": [c("net", "cmd.exe /c \"echo AF network-device-firewall proxy - run 'show access-lists' read-only on your own device\"",
                    "Placeholder — read your own device ACLs read-only.")],
    "T1686.003": [c("windows", "netsh advfirewall firewall show rule name=all | more & echo AF Windows-host-firewall proxy (read-only)",
                    "Lists firewall rules (read-only; nothing changed).")],
    "T1689": [c("windows", "cmd.exe /c \"echo AF downgrade-attack proxy - no protocol/tool downgraded\"",
                "Placeholder only.")],
    "T1690": [c("windows", "powershell -NoProfile -Command \"Get-PSReadlineOption|Select HistorySavePath; 'prevent-history-logging proxy (read-only)'\"",
                "Reads the history-logging config (read-only; logging left enabled).")],
    # ---- Hide artifacts ----
    "T1564.001": [c("windows", "echo AF > %TEMP%\\af_hidden.txt & attrib +h %TEMP%\\af_hidden.txt & dir /a:h %TEMP%\\af_hidden.txt & attrib -h %TEMP%\\af_hidden.txt & del %TEMP%\\af_hidden.txt",
                    "Sets/clears the hidden attribute on a temp file (hidden-files proxy).")],
    "T1564.002": [c("windows", "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList\" 2>nul & echo AF hidden-users proxy (read-only)",
                    "Reads the hidden-users registry path (read-only).")],
    "T1564.003": [c("windows", "powershell -NoProfile -WindowStyle Hidden -Command \"'AF hidden-window proxy ran'\"",
                    "Runs a lab command in a hidden window (hidden-window proxy).")],
    "T1564.004": [c("windows", "echo AF > %TEMP%\\af_host.txt & echo hidden > %TEMP%\\af_host.txt:secret & dir /r %TEMP%\\af_host.txt & del %TEMP%\\af_host.txt",
                    "Writes/reads an NTFS alternate data stream (NTFS-file-attributes proxy).")],
    "T1564.005": [c("windows", "mountvol & echo AF hidden-file-system proxy (list volumes read-only)",
                    "Lists mount points (hidden-file-system proxy; read-only).")],
    "T1564.008": [c("windows", "cmd.exe /c \"echo AF email-hiding-rules proxy - no inbox rule created\"",
                    "Placeholder only.")],
    "T1564.011": [c("windows", "cmd.exe /c \"echo AF ignore-process-interrupts proxy - no handler modified\"",
                    "Placeholder only.")],
    "T1564.012": [c("windows", "powershell -NoProfile -Command \"Get-MpPreference|Select -ExpandProperty ExclusionPath -EA SilentlyContinue; 'file/path-exclusions proxy (read-only)'\"",
                    "Reads existing AV exclusions (read-only; none added).")],
    "T1564.013": [c("linux", "mount | head & echo 'AF bind-mounts proxy (read-only, nothing mounted)'",
                    "Lists mounts (read-only).")],
    # ---- Guardrails / permissions / GPO ----
    "T1480": [c("windows", "powershell -NoProfile -Command \"if($env:COMPUTERNAME){'guardrail check passed (proxy)'}\"",
                "Lab environment check (execution-guardrails proxy).")],
    "T1480.001": [c("windows", "powershell -NoProfile -Command \"$env:USERDOMAIN\"",
                    "Reads a domain value used for keying (environmental-keying proxy).")],
    "T1480.002": [c("windows", "powershell -NoProfile -Command \"$m=New-Object Threading.Mutex($false,'AF_mutex'); $m.Close(); 'mutex created/closed (proxy)'\"",
                    "Creates/closes a lab mutex (mutual-exclusion proxy).")],
    "T1484.001": [c("windows", "gpresult /scope computer /r 2>nul | more & echo AF group-policy-modification proxy (read-only)",
                    "Reads applied GPOs (read-only; nothing modified).")],
    "T1484.002": [c("windows", "nltest /domain_trusts 2>nul & echo AF domain-trust-modification proxy (read-only)",
                    "Reads domain trusts (read-only; nothing modified).")],
    "T1222.001": [c("windows", "icacls %TEMP%\\af_perm.txt 2>nul & echo AF > %TEMP%\\af_perm.txt & icacls %TEMP%\\af_perm.txt /grant %USERNAME%:R & del %TEMP%\\af_perm.txt",
                    "Modifies ACLs on a temp file (Windows-permissions proxy).")],
    "T1222.002": [c("linux", "touch /tmp/af_perm && chmod 600 /tmp/af_perm && stat -c '%a' /tmp/af_perm && rm -f /tmp/af_perm",
                    "chmod on a temp file (Linux/Mac-permissions proxy).")],
    "T1497.002": [c("windows", "powershell -NoProfile -Command \"(Get-CimInstance Win32_ComputerSystem).UserName\"",
                    "Reads interactive user (user-activity-based sandbox check).")],
    "T1497.003": [c("windows", "powershell -NoProfile -Command \"$t=Get-Date; Start-Sleep -Milliseconds 500; ((Get-Date)-$t).TotalMilliseconds\"",
                    "Measures a short sleep (time-based sandbox check).")],
    "T1599": [c("net", "cmd.exe /c \"echo AF network-boundary-bridging proxy - inspect your own device routing read-only\"",
                "Placeholder — inspect your own device routing read-only.")],
}
