"""Extended lab commands — Part 9: Execution."""
from .ext_helper import c

PART = {
    "T1053": [c("windows", "schtasks /Query /FO LIST /TN \\Microsoft\\Windows\\* 2>nul | more & echo AF scheduled-task/job proxy (list only)",
                "Lists scheduled tasks (read-only).")],
    "T1053.002": [c("windows", "at 2>nul & echo AF 'at' proxy (deprecated at.exe invoked with no job)",
                    "Invokes at.exe with no arguments (proxy; no job scheduled).")],
    "T1059": [c("windows", "powershell -NoProfile -Command \"$PSVersionTable.PSVersion\" & cmd /c ver",
                "Invokes both script interpreters benignly (command-and-scripting-interpreter proxy).")],
    "T1059.008": [c("net", "cmd.exe /c \"echo AF network-device-CLI proxy - run 'show version' read-only on your own device\"",
                    "Placeholder — read your own device via its CLI.")],
    "T1059.009": [c("cloud", "az account show -o table 2>nul || aws sts get-caller-identity 2>nul & echo AF cloud-API proxy (read-only whoami)",
                    "Read-only cloud identity call (cloud-API proxy; requires CLI auth).")],
    "T1059.010": [c("windows", "where AutoHotkey.exe AutoIt3.exe 2>nul & echo AF AutoHotKey/AutoIT proxy (locate only, nothing run)",
                    "Locates AHK/AutoIt (proxy; nothing run).")],
    "T1059.012": [c("linux", "echo 'AF hypervisor-CLI proxy - run esxcli system version get read-only on your own host'",
                    "Placeholder — read-only hypervisor CLI on your own host.")],
    "T1059.013": [c("other", "docker version 2>/dev/null; echo AF container-CLI/API proxy (read-only version)",
                    "Read-only container runtime version (container-CLI proxy).")],
    "T1072": [c("windows", "powershell -NoProfile -Command \"Get-Service|? {$_.DisplayName -match 'SCCM|BigFix|Intune|Tanium'}|Select Name,Status\"",
                "Enumerates deployment-tool agents (software-deployment-tools proxy; read-only).")],
    "T1204.001": [c("windows", "powershell -NoProfile -Command \"Start-Process 'https://example.com'\" & echo AF malicious-link proxy (opens example URL)",
                    "Opens an example URL in the default handler (malicious-link proxy).")],
    "T1204.003": [c("cloud", "docker images 2>/dev/null; echo AF malicious-image proxy (list local images read-only)",
                    "Lists local container images (malicious-image proxy; read-only).")],
    "T1204.004": [c("windows", "powershell -NoProfile -Command \"Set-Clipboard 'echo AF malicious-copy-paste proxy'; Get-Clipboard\"",
                    "Round-trips a lab string through the clipboard (copy-paste proxy).")],
    "T1204.005": [c("windows", "cmd.exe /c \"echo AF malicious-library proxy - no library loaded\"",
                    "Placeholder only.")],
    "T1559": [c("windows", "powershell -NoProfile -Command \"[Type]::GetTypeFromProgID('Shell.Application') -ne $null\"",
                "References a COM/IPC endpoint (inter-process-communication proxy).")],
    "T1559.001": [c("windows", "powershell -NoProfile -Command \"$s=New-Object -ComObject Shell.Application; $s.GetType().Name; [void][Runtime.InteropServices.Marshal]::ReleaseComObject($s)\"",
                    "Creates+releases a lab COM object (component-object-model proxy).")],
    "T1559.002": [c("windows", "cmd.exe /c \"echo AF dynamic-data-exchange (DDE) proxy - no document/DDE field created\"",
                    "Placeholder only.")],
    "T1609": [c("other", "kubectl version --client 2>/dev/null; docker version 2>/dev/null; echo AF container-administration-command proxy (read-only)",
                "Read-only container admin version call (proxy).")],
    "T1610": [c("other", "docker images 2>/dev/null | head; echo AF deploy-container proxy (list images only, nothing deployed)",
                "Lists images (deploy-container proxy; nothing deployed).")],
    "T1651": [c("cloud", "az vm run-command list --help 2>nul & echo AF cloud-administration-command proxy (help only, nothing run)",
                "Read-only proxy for cloud run-command (nothing executed).")],
    "T1675": [c("linux", "echo 'AF ESXi-administration-command proxy - run esxcli system hostname get read-only on your own host'",
                "Placeholder — read-only ESXi admin command on your own host.")],
    "T1677": [c("cloud", "cmd.exe /c \"echo AF poisoned-pipeline-execution proxy - no CI/CD pipeline modified\"",
                "Placeholder only.")],
}
