"""Extended lab commands — Part 6: Defense Evasion — obfuscation & masquerading."""
from .ext_helper import c

PART = {
    "T1006": [c("windows", "fsutil fsinfo ntfsinfo C: 2>nul | more & echo AF direct-volume-access proxy (read-only volume info)",
                "Reads NTFS volume info (direct-volume-access proxy; no raw handle opened).")],
    "T1014": [c("windows", "powershell -NoProfile -Command \"Get-CimInstance Win32_SystemDriver|? State -eq Running|Select -First 5 Name\"",
                "Lists running kernel drivers (rootkit proxy; read-only).")],
    "T1027": [c("windows", "powershell -NoProfile -Command \"[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('AF'))\"",
                "Base64-encodes a marker (obfuscated-files proxy).")],
    "T1027.001": [c("windows", "fsutil file createnew %TEMP%\\af_pad.bin 1048576 & echo AF binary-padding proxy (1MB junk file)",
                    "Creates a padded file (binary-padding proxy).", "del %TEMP%\\af_pad.bin 2>nul")],
    "T1027.002": [c("windows", "cmd.exe /c \"echo AF software-packing proxy - no packer run (e.g. UPX not invoked)\"",
                    "Bounded lab simulation only.")],
    "T1027.003": [c("windows", "powershell -NoProfile -Command \"Add-Content $env:TEMP\\af_img.txt 'hidden:AF'; (Get-Item $env:TEMP\\af_img.txt).Length\"",
                    "Hides a marker in a file (steganography proxy).", "del %TEMP%\\af_img.txt 2>nul")],
    "T1027.004": [c("windows", "where csc.exe 2>nul & echo AF compile-after-delivery proxy (locate compiler, nothing compiled)",
                    "Locates the C# compiler (compile-after-delivery proxy).")],
    "T1027.005": [c("windows", "cmd.exe /c \"echo AF indicator-removal-from-tools proxy - no tool modified\"",
                    "Bounded lab simulation only.")],
    "T1027.006": [c("windows", "powershell -NoProfile -Command \"Set-Content $env:TEMP\\af.html '<script>var b=atob(\\\"QUY=\\\")</script>'; 'HTML-smuggling proxy file written'\"",
                    "Writes a lab HTML file with base64 (HTML-smuggling proxy).", "del %TEMP%\\af.html 2>nul")],
    "T1027.007": [c("windows", "powershell -NoProfile -Command \"[Runtime.InteropServices.Marshal].GetMethod('GetProcAddress') -ne $null\"",
                    "References dynamic-resolution API by reflection (dynamic-API-resolution proxy).")],
    "T1027.009": [c("windows", "powershell -NoProfile -Command \"$p=[Convert]::FromBase64String('QUY='); $p.Length\"",
                    "Decodes an embedded blob locally (embedded-payloads proxy).")],
    "T1027.010": [c("windows", "cmd.exe /c \"set x=who&&set y=ami&&call echo %x%%y%\"",
                    "Splits a command via env vars (command-obfuscation proxy).")],
    "T1027.011": [c("windows", "reg add HKCU\\Software\\AdversaryFlow /v blob /t REG_SZ /d QUY= /f & echo AF fileless-storage proxy",
                    "Stores a lab blob in the registry (fileless-storage proxy).", "reg delete HKCU\\Software\\AdversaryFlow /f")],
    "T1027.012": [c("windows", "cmd.exe /c \"echo AF LNK-icon-smuggling proxy - no shortcut crafted\"",
                    "Bounded lab simulation only.")],
    "T1027.013": [c("windows", "certutil -encode %WINDIR%\\win.ini %TEMP%\\af_enc.b64 & echo AF encrypted/encoded-file proxy",
                    "Encodes a lab file (encrypted/encoded-file proxy).", "del %TEMP%\\af_enc.b64 2>nul")],
    "T1027.015": [c("windows", "powershell -NoProfile -Command \"Compress-Archive $env:WINDIR\\win.ini $env:TEMP\\af_c.zip -Force; 'compressed'\"",
                    "Compresses a lab file (compression proxy).", "del %TEMP%\\af_c.zip 2>nul")],
    "T1027.016": [c("windows", "cmd.exe /c \"echo AF junk-code-insertion proxy - no binary modified\"",
                    "Bounded lab simulation only.")],
    "T1036.001": [c("windows", "powershell -NoProfile -Command \"Get-AuthenticodeSignature $env:WINDIR\\System32\\calc.exe|Select Status\"",
                    "Reads a signature status (invalid-code-signature proxy; read-only).")],
    "T1036.002": [c("windows", "powershell -NoProfile -Command \"'exe' + [char]0x202E + 'cod.'\"",
                    "Builds a string with the RTL-override char (right-to-left-override proxy; no file created).")],
    "T1036.003": [c("windows", "copy %WINDIR%\\System32\\cmd.exe %TEMP%\\af_totally_legit.exe & echo AF rename-legitimate-utility proxy",
                    "Copies cmd.exe under a lab new name (rename-utility proxy).", "del %TEMP%\\af_totally_legit.exe 2>nul")],
    "T1036.004": [c("windows", "sc.exe query type= service | more",
                    "Lists services (masquerading-service-name proxy). Does not create a service.")],
    "T1036.005": [c("windows", "copy %WINDIR%\\System32\\calc.exe %TEMP%\\svchost.exe & echo AF match-legitimate-name proxy",
                    "Copies calc under a legitimate-looking name (masquerade proxy).", "del %TEMP%\\svchost.exe 2>nul")],
    "T1036.006": [c("linux", "touch '/tmp/af_report.pdf ' && ls -la /tmp/ | grep af_report && rm -f '/tmp/af_report.pdf '",
                    "Creates a file with a trailing space (space-after-filename proxy).")],
    "T1036.007": [c("windows", "echo AF > \"%TEMP%\\af_invoice.pdf.exe\" & dir \"%TEMP%\\af_invoice.pdf.exe\" & del \"%TEMP%\\af_invoice.pdf.exe\"",
                    "Creates a double-extension file (double-file-extension proxy).")],
    "T1036.008": [c("windows", "echo MZ-not-really > %TEMP%\\af_doc.pdf & echo AF masquerade-file-type proxy & del %TEMP%\\af_doc.pdf",
                    "Writes mismatched content/extension (masquerade-file-type proxy).")],
    "T1036.010": [c("windows", "net user",
                    "Lists local accounts (masquerade-account-name proxy). Does not create an account.")],
    "T1211": [c("windows", "cmd.exe /c \"echo AF exploitation-for-defense-evasion proxy - no exploit run\"",
                "Bounded lab simulation only.")],
    "T1620": [c("windows", "powershell -NoProfile -Command \"[Reflection.Assembly]::Load([IO.File]::ReadAllBytes($env:WINDIR+'\\System32\\mscorlib.dll')).FullName -ne $null 2>$null; 'reflective-load proxy'\"",
                "References reflective assembly loading (reflective-code-loading proxy).")],
    "T1622": [c("windows", "powershell -NoProfile -Command \"[System.Diagnostics.Debugger]::IsAttached\"",
                "Checks for an attached debugger (debugger-evasion proxy; read-only).")],
}
