"""Extended lab commands — Part 8: Defense Evasion — proxy execution, injection, tokens, hijack flow."""
from .ext_helper import c

_NP = "spawns+kills notepad as a lab process-interaction proxy — no injection."
_KILL = "taskkill /IM notepad.exe /F 2>nul"

PART = {
    # ---- Process injection family (all notepad spawn/kill proxies) ----
    "T1055.001": [c("windows", "powershell -NoProfile -Command \"$p=Start-Process notepad -PassThru; Start-Sleep 1; Stop-Process $p.Id\"",
                    "DLL-injection proxy — " + _NP, _KILL)],
    "T1055.002": [c("windows", "powershell -NoProfile -Command \"$p=Start-Process notepad -PassThru; Start-Sleep 1; Stop-Process $p.Id\"",
                    "PE-injection proxy — " + _NP, _KILL)],
    "T1055.004": [c("windows", "powershell -NoProfile -Command \"$p=Start-Process notepad -PassThru; Start-Sleep 1; Stop-Process $p.Id\"",
                    "APC-injection proxy — " + _NP, _KILL)],
    "T1055.009": [c("linux", "cat /proc/self/maps | head & echo 'AF proc-memory proxy (reads own maps, read-only)'",
                    "Reads the process's own memory map (proc-memory proxy; read-only).")],
    "T1055.012": [c("windows", "powershell -NoProfile -Command \"$p=Start-Process notepad -PassThru; Start-Sleep 1; Stop-Process $p.Id\"",
                    "Process-hollowing proxy — " + _NP, _KILL)],
    "T1055.013": [c("windows", "powershell -NoProfile -Command \"$p=Start-Process notepad -PassThru; Start-Sleep 1; Stop-Process $p.Id\"",
                    "Process-doppelganging proxy — " + _NP, _KILL)],
    # ---- Access token manipulation ----
    "T1134.001": [c("windows", "whoami /priv | findstr /i SeImpersonate & echo AF token-impersonation proxy (read-only)",
                    "Reads impersonation privilege (token-impersonation proxy; read-only).")],
    "T1134.002": [c("windows", "runas /? >nul & echo AF create-process-with-token proxy (runas available, not invoked)",
                    "References runas (create-process-with-token proxy; nothing launched).")],
    "T1134.003": [c("windows", "whoami /groups | more & echo AF make-and-impersonate-token proxy (read-only)",
                    "Reads token groups (make/impersonate-token proxy; read-only).")],
    # ---- System binary proxy execution (LOLBins) ----
    "T1218": [c("windows", "where rundll32.exe & echo AdversaryFlow lab rundll32 locate — screen is not locked",
                "Locates rundll32.exe without invoking LockWorkStation or any other export.")],
    "T1218.001": [c("windows", "hh.exe about: & echo AF compiled-HTML-file (hh.exe) proxy & timeout 1 >nul & taskkill /IM hh.exe /F 2>nul",
                    "Launches the CHM host against a blank page (compiled-HTML-file proxy).")],
    "T1218.003": [c("windows", "cmd.exe /c \"echo AF CMSTP proxy - no INF supplied\"", "Bounded lab simulation only — no INF is processed.")],
    "T1218.004": [c("windows", "where InstallUtil.exe 2>nul & echo AF InstallUtil proxy (locate only, nothing installed)",
                    "Locates InstallUtil (proxy; nothing installed).")],
    "T1218.007": [c("windows", "msiexec /? & echo AF Msiexec proxy (help dialog only, no package installed)",
                    "Opens msiexec help (Msiexec proxy; nothing installed).")],
    "T1218.008": [c("windows", "where odbcconf.exe 2>nul & echo AF Odbcconf proxy (locate only)",
                    "Locates odbcconf (proxy; nothing run).")],
    "T1218.010": [c("windows", "regsvr32 /? & echo AF Regsvr32 proxy (help dialog only, no DLL registered)",
                    "Opens regsvr32 help (Regsvr32 proxy; nothing registered).")],
    "T1218.014": [c("windows", "where mmc.exe 2>nul & echo AF MMC proxy (locate only, no snap-in loaded)",
                    "Locates mmc (proxy; nothing loaded).")],
    "T1218.015": [c("windows", "cmd.exe /c \"echo AF Electron-application proxy - no app launched with abusive flags\"",
                    "Bounded lab simulation only.")],
    "T1220": [c("windows", "where wmic.exe 2>nul & echo AF XSL-script-processing proxy (locate only, no XSL run)",
                "Locates wmic (XSL-script-processing proxy; nothing run).")],
    "T1221": [c("windows", "cmd.exe /c \"echo AF template-injection proxy - no document template modified\"",
                "Bounded lab simulation only.")],
    "T1216.001": [c("windows", "where cscript.exe 2>nul & echo AF PubPrn proxy (locate script host only)",
                    "Locates the script host (PubPrn proxy; nothing executed).")],
    "T1127.001": [c("windows", "where msbuild.exe 2>nul & echo AF MSBuild proxy (locate only, no project built)",
                    "Locates MSBuild (proxy; nothing built).")],
    "T1202": [c("windows", "forfiles /p %WINDIR% /m notepad.exe /c \"cmd /c echo AF indirect-command-execution proxy\" 2>nul",
                "Uses forfiles to run a lab echo (indirect-command-execution proxy).")],
    # ---- Elevation / alternate auth ----
    "T1548": [c("windows", "whoami /groups | findstr /i S-1-16 & echo AF abuse-elevation-control proxy (read integrity level)",
                "Reads integrity level (abuse-elevation-control proxy; read-only).")],
    "T1550": [c("windows", "cmdkey /list & echo AF use-alternate-authentication-material proxy (list only)",
                "Lists cached auth material (read-only).")],
    "T1550.001": [c("cloud", "az account get-access-token --query expiresOn -o tsv 2>nul & echo AF application-access-token proxy (own token metadata)",
                    "Reads your own token metadata (read-only; requires cloud CLI auth).")],
    "T1550.002": [c("windows", "klist & echo AF pass-the-hash proxy (list creds/tickets only, no hash reused)",
                    "Lists cached tickets (pass-the-hash proxy; read-only).")],
    "T1550.003": [c("windows", "klist & echo AF pass-the-ticket proxy (list tickets only, no ticket injected)",
                    "Lists Kerberos tickets (pass-the-ticket proxy; read-only).")],
    "T1550.004": [c("cloud", "cmd.exe /c \"echo AF web-session-cookie proxy - no cookie replayed\"",
                    "Bounded lab simulation only.")],
    # ---- Hijack execution flow ----
    "T1574": [c("windows", "where whoami.exe & echo AF hijack-execution-flow proxy (resolve search order read-only)",
                "Resolves binary search order (hijack-execution-flow proxy; read-only).")],
    "T1574.001": [c("windows", "cmd.exe /c \"echo AF DLL-search-order/side-load proxy - no DLL planted\"",
                    "Bounded lab simulation only — no DLL is planted.")],
    "T1574.005": [c("windows", "icacls \"%ProgramFiles%\" 2>nul | more & echo AF installer-file-permissions proxy (read-only)",
                    "Reads installer directory ACLs (read-only).")],
    "T1574.006": [c("linux", "echo $LD_PRELOAD & echo 'AF dynamic-linker-hijacking proxy (read LD_PRELOAD, nothing set)'",
                    "Reads LD_PRELOAD (dynamic-linker-hijacking proxy; nothing set).")],
    "T1574.011": [c("windows", "powershell -NoProfile -Command \"Get-Acl HKLM:\\SYSTEM\\CurrentControlSet\\Services|Select -First 1 Owner\"",
                    "Reads service registry ACLs (services-registry-permissions proxy; read-only).")],
    "T1574.012": [c("windows", "reg query HKCU\\Environment /v COR_PROFILER 2>nul & echo AF COR_PROFILER proxy (read-only, none set)",
                    "Reads the COR_PROFILER value (read-only; nothing set).")],
    "T1574.013": [c("windows", "cmd.exe /c \"echo AF KernelCallbackTable-hijack proxy - no process manipulated\"",
                    "Bounded lab simulation only.")],
}
