"""Extended lab commands — Part 10: Persistence."""
from .ext_helper import c

PART = {
    "T1037": [c("windows", "reg query \"HKCU\\Environment\" /v UserInitMprLogonScript 2>nul & echo AF logon-init-scripts proxy (read-only)",
                "Reads the logon-script value (read-only; nothing set).")],
    "T1037.001": [c("windows", "reg query \"HKCU\\Environment\" /v UserInitMprLogonScript 2>nul & echo AF logon-script-Windows proxy (read-only)",
                    "Reads the Windows logon-script value (read-only).")],
    "T1037.004": [c("linux", "ls -la /etc/rc.local /etc/rc.d/ 2>/dev/null; echo 'AF RC-scripts proxy (list only, nothing added)'",
                    "Lists RC-script locations (read-only).")],
    "T1098.001": [c("cloud", "az ad app credential list --help 2>nul & echo AF additional-cloud-credentials proxy (help only, nothing added)",
                    "Read-only proxy (no credential added; requires cloud CLI auth).")],
    "T1098.002": [c("windows", "cmd.exe /c \"echo AF additional-email-delegate-permissions proxy - no mailbox delegation changed\"",
                    "Placeholder only.")],
    "T1098.003": [c("cloud", "az role assignment list --all -o table 2>nul & echo AF additional-cloud-roles proxy (list only, nothing granted)",
                    "Lists role assignments (read-only; requires cloud CLI auth).")],
    "T1098.004": [c("linux", "ls -la ~/.ssh/authorized_keys 2>/dev/null; echo 'AF SSH-authorized-keys proxy (read-only, no key added)'",
                    "Reads authorized_keys metadata (read-only; no key added).")],
    "T1098.005": [c("windows", "dsregcmd /status 2>nul | findstr /i DeviceId & echo AF device-registration proxy (read-only)",
                    "Reads device-join status (read-only; no device registered).")],
    "T1098.007": [c("windows", "net localgroup Administrators & echo AF additional-local/domain-groups proxy (read-only, nobody added)",
                    "Reads admin-group membership (read-only; nobody added).")],
    "T1133": [c("windows", "powershell -NoProfile -Command \"Get-Service TermService,SSHD -EA SilentlyContinue|Select Name,Status\"",
                "Enumerates remote-access services (external-remote-services proxy; read-only).")],
    "T1136": [c("windows", "net user AdversaryFlowTmp * /add & echo AF create-account proxy (requires admin; enter a unique temporary password)",
                "Creates a lab local account and prompts for a unique password.", "net user AdversaryFlowTmp /delete")],
    "T1136.002": [c("windows", "cmd.exe /c \"echo AF create-domain-account proxy - no domain account created\"",
                    "Placeholder only (avoids creating a domain account).")],
    "T1136.003": [c("cloud", "cmd.exe /c \"echo AF create-cloud-account proxy - no cloud account created\"",
                    "Placeholder only.")],
    "T1137": [c("windows", "dir /s /b \"%AppData%\\Microsoft\\Templates\\*.dotm\" 2>nul & echo AF office-application-startup proxy (read-only)",
                "Locates Office templates (read-only).")],
    "T1137.001": [c("windows", "dir /s /b \"%AppData%\\Microsoft\\Word\\STARTUP\" 2>nul & echo AF office-template-macros proxy (read-only)",
                    "Reads the Office STARTUP path (read-only).")],
    "T1137.002": [c("windows", "reg query \"HKCU\\Software\\Microsoft\\Office test\\Special\\Perf\" 2>nul & echo AF office-test proxy (read-only, nothing set)",
                    "Reads the Office Test registry path (read-only; nothing set).")],
    "T1137.004": [c("windows", "cmd.exe /c \"echo AF outlook-home-page proxy - no Outlook home page configured\"",
                    "Placeholder only.")],
    "T1137.006": [c("windows", "dir /s /b \"%AppData%\\Microsoft\\AddIns\\*\" 2>nul & echo AF office-add-ins proxy (read-only)",
                    "Lists Office add-ins (read-only).")],
    "T1176.001": [c("windows", "dir /s /b \"%LocalAppData%\\Google\\Chrome\\User Data\\Default\\Extensions\" 2>nul | more & echo AF browser-extensions proxy (list only)",
                    "Lists installed browser extensions (read-only).")],
    "T1176.002": [c("windows", "dir /s /b \"%UserProfile%\\.vscode\\extensions\" 2>nul | more & echo AF IDE-extensions proxy (list only)",
                    "Lists installed IDE extensions (read-only).")],
    "T1505.001": [c("windows", "cmd.exe /c \"echo AF SQL-stored-procedures proxy - no stored procedure created\"",
                    "Placeholder only.")],
    "T1505.004": [c("windows", "powershell -NoProfile -Command \"Get-WindowsOptionalFeature -Online -FeatureName IIS-* -EA SilentlyContinue|? State -eq Enabled|Select -First 3 FeatureName\"",
                    "Enumerates IIS features (IIS-components proxy; read-only).")],
    "T1505.006": [c("linux", "echo 'AF vSphere-installation-bundles proxy - list VIBs read-only: esxcli software vib list'",
                    "Placeholder — read-only VIB listing on your own host.")],
    "T1542.002": [c("windows", "cmd.exe /c \"echo AF component-firmware proxy - firmware not modified\"",
                    "Placeholder only.")],
    "T1542.003": [c("windows", "bcdedit /enum {bootmgr} 2>nul & echo AF bootkit proxy (read boot config only, nothing modified)",
                    "Reads boot config (bootkit proxy; nothing modified).")],
    "T1543.001": [c("macos", "launchctl list | head & echo 'AF launch-agent proxy (list only, nothing installed)'",
                    "Lists launch agents (read-only).")],
    "T1543.002": [c("linux", "systemctl list-units --type=service --no-pager | head & echo 'AF systemd-service proxy (list only)'",
                    "Lists systemd services (read-only).")],
    "T1543.004": [c("macos", "launchctl list | grep -i daemon | head & echo 'AF launch-daemon proxy (list only)'",
                    "Lists launch daemons (read-only).")],
    "T1546": [c("windows", "powershell -NoProfile -Command \"Get-WmiObject __EventFilter -Namespace root\\subscription -EA SilentlyContinue|Select Name\"",
                "Reads WMI event subscriptions (event-triggered-execution proxy; read-only).")],
    "T1546.001": [c("windows", "assoc .txt & ftype txtfile & echo AF change-default-file-association proxy (read-only)",
                    "Reads a file association (read-only; nothing changed).")],
    "T1546.004": [c("linux", "grep -n . ~/.bashrc 2>/dev/null | tail & echo 'AF unix-shell-config proxy (read-only, nothing appended)'",
                    "Reads shell rc file (read-only; nothing appended).")],
    "T1546.008": [c("windows", "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\sethc.exe\" 2>nul & echo AF accessibility-features proxy (read-only)",
                    "Reads the sethc IFEO key (accessibility-features proxy; read-only).")],
    "T1546.010": [c("windows", "reg query \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows\" /v AppInit_DLLs 2>nul & echo AF AppInit-DLLs proxy (read-only)",
                    "Reads the AppInit_DLLs value (read-only; nothing set).")],
    "T1546.011": [c("windows", "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Custom\" 2>nul & echo AF application-shimming proxy (read-only)",
                    "Reads the shim database registry path (read-only).")],
    "T1546.012": [c("windows", "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\" 2>nul | more & echo AF IFEO-injection proxy (read-only)",
                    "Reads IFEO keys (read-only; nothing set).")],
    "T1546.013": [c("windows", "powershell -NoProfile -Command \"Test-Path $PROFILE; 'PowerShell-profile proxy (checked existence, nothing written)'\"",
                    "Checks for a PowerShell profile (read-only; nothing written).")],
    "T1546.015": [c("windows", "reg query \"HKCU\\Software\\Classes\\CLSID\" 2>nul | more & echo AF COM-hijacking proxy (read-only)",
                    "Reads user COM CLSID keys (read-only; nothing hijacked).")],
    "T1546.016": [c("windows", "cmd.exe /c \"echo AF installer-packages (event-triggered) proxy - no package installed\"",
                    "Placeholder only.")],
    "T1547": [c("windows", "reg query HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run & echo AF boot/logon-autostart proxy (read-only)",
                "Reads autostart Run keys (read-only).")],
    "T1547.004": [c("windows", "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /v Shell 2>nul & echo AF Winlogon-helper proxy (read-only)",
                    "Reads the Winlogon Shell value (read-only).")],
    "T1547.006": [c("linux", "lsmod | head & echo 'AF kernel-modules proxy (list only, nothing loaded)'",
                    "Lists loaded kernel modules (read-only).")],
    "T1547.009": [c("windows", "powershell -NoProfile -Command \"Get-ChildItem $env:APPDATA\\Microsoft\\Windows\\'Start Menu'\\Programs -Filter *.lnk -Recurse -EA SilentlyContinue|Select -First 3 Name\"",
                    "Lists shortcut files (shortcut-modification proxy; read-only).")],
    "T1547.012": [c("windows", "reg query \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Print\\Environments\\Windows x64\\Print Processors\" 2>nul & echo AF print-processors proxy (read-only)",
                    "Reads print-processor keys (read-only).")],
    "T1547.013": [c("linux", "ls -la ~/.config/autostart/ /etc/xdg/autostart/ 2>/dev/null | head & echo 'AF XDG-autostart proxy (list only)'",
                    "Lists XDG autostart entries (read-only).")],
    "T1653": [c("windows", "powercfg /query 2>nul | more & echo AF power-settings proxy (read-only)",
                "Reads power settings (read-only; nothing changed).")],
    "T1554": [c("windows", "powershell -NoProfile -Command \"Get-AuthenticodeSignature $env:WINDIR\\System32\\notepad.exe|Select Status\"",
                "Reads a system binary signature (compromise-host-binary proxy; read-only, unmodified).")],
}
