"""Extended lab commands — Part 1: Command & Control (application layer, proxy, encoding)."""
from .ext_helper import c

PART = {
    "T1001": [c("windows", "powershell -NoProfile -Command \"-join('AdversaryFlow'.ToCharArray()|%{[int][char]$_})\"",
                "Lab data-obfuscation proxy (encodes a marker string locally).")],
    "T1001.001": [c("windows", "powershell -NoProfile -Command \"([byte[]](1..64|%{Get-Random -Max 255})).Length\"",
                    "Generates junk bytes locally (junk-data padding proxy; nothing sent).")],
    "T1001.002": [c("windows", "powershell -NoProfile -Command \"Add-Content $env:TEMP\\af_stego.txt 'AF marker'; (Get-Item $env:TEMP\\af_stego.txt).Length\"",
                    "Steganography proxy — hides a marker in a temp file.", "del %TEMP%\\af_stego.txt 2>nul")],
    "T1001.003": [c("windows", "powershell -NoProfile -Command \"Invoke-WebRequest https://example.com -UserAgent 'Mozilla/5.0' -UseBasicParsing|Select StatusCode\"",
                    "Sends a browser-like UA to an example host (protocol impersonation proxy).")],
    "T1008": [c("windows", "nslookup example.com & nslookup example.com 8.8.8.8",
                "Resolves via primary then fallback resolver (fallback-channel proxy).")],
    "T1071": [c("windows", "powershell -NoProfile -Command \"Invoke-WebRequest https://example.com -UseBasicParsing|Select StatusCode\"",
                "Lab HTTPS request to an example host (application-layer C2 proxy).")],
    "T1071.002": [c("windows", "powershell -NoProfile -Command \"(New-Object Net.WebClient).DownloadString('https://example.com')|Out-Null; 'ok'\"",
                    "Lab file-transfer-protocol style fetch to an example host.")],
    "T1071.003": [c("windows", "powershell -NoProfile -Command \"Test-NetConnection example.com -Port 25|Select TcpTestSucceeded\"",
                    "Single lab SMTP port check (mail-protocol C2 proxy; no mail sent).")],
    "T1071.004": [c("windows", "nslookup -type=TXT example.com",
                    "Lab DNS TXT lookup (DNS C2 proxy).")],
    "T1090.001": [c("windows", "netsh interface portproxy show all & echo AF internal-proxy config read (read-only)",
                    "Read-only view of local port-proxy config.")],
    "T1090.002": [c("windows", "powershell -NoProfile -Command \"[Net.WebRequest]::DefaultWebProxy.GetProxy('https://example.com')\"",
                    "Resolves the configured external proxy for an example host (read-only).")],
    "T1090.003": [c("windows", "nslookup example.com & echo AF multi-hop-proxy proxy - single lab resolution only",
                    "Lab DNS lookup as a multi-hop-proxy placeholder.")],
    "T1090.004": [c("windows", "powershell -NoProfile -Command \"Invoke-WebRequest https://example.com -Headers @{Host='example.com'} -UseBasicParsing|Select StatusCode\"",
                    "Sets an explicit Host header to an example host (domain-fronting proxy).")],
    "T1092": [c("windows", "powershell -NoProfile -Command \"Get-Volume|? DriveType -eq 'Removable'|Select DriveLetter\"",
                "Enumerates removable media (removable-media C2 proxy; read-only).")],
    "T1095": [c("windows", "ping -n 2 example.com",
                "Lab ICMP echo (non-application-layer protocol C2 proxy).")],
    "T1102": [c("windows", "powershell -NoProfile -Command \"Invoke-WebRequest https://example.com -UseBasicParsing|Select StatusCode\"",
                "Lab request to a legitimate web service (web-service C2 proxy).")],
    "T1102.001": [c("windows", "powershell -NoProfile -Command \"(Invoke-WebRequest https://example.com -UseBasicParsing).Content.Length\"",
                    "Reads content from an example host (dead-drop-resolver proxy; nothing parsed as C2).")],
    "T1102.002": [c("windows", "powershell -NoProfile -Command \"(Invoke-WebRequest https://example.com -Method GET -UseBasicParsing).StatusCode\"",
                    "Single lab request/response to an example host (bidirectional-comms proxy).")],
    "T1102.003": [c("windows", "powershell -NoProfile -Command \"(Invoke-WebRequest https://example.com -Method GET -UseBasicParsing).StatusCode\"",
                    "One-way lab GET to an example host (one-way-comms proxy).")],
    "T1104": [c("windows", "nslookup example.com & powershell -NoProfile -Command \"Invoke-WebRequest https://example.com -UseBasicParsing|Select StatusCode\"",
                "Two lab staged requests (multi-stage-channel proxy).")],
    "T1132": [c("windows", "powershell -NoProfile -Command \"[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('AdversaryFlow'))\"",
                "Base64-encodes a marker (data-encoding proxy).")],
    "T1132.001": [c("windows", "powershell -NoProfile -Command \"[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes('AF'))\"",
                    "Standard base64 encoding of a marker (standard-encoding proxy).")],
    "T1132.002": [c("windows", "powershell -NoProfile -Command \"(([Text.Encoding]::UTF8.GetBytes('AF'))|%{'{0:x2}' -f $_}) -join ''\"",
                    "Hex (non-standard) encoding of a marker (non-standard-encoding proxy).")],
    "T1205": [c("windows", "ping -n 1 -l 1 example.com & echo AF traffic-signaling proxy (single lab packet)",
                "Single crafted-size lab ping (traffic-signaling proxy).")],
    "T1205.001": [c("windows", "powershell -NoProfile -Command \"1..3|%{Test-NetConnection example.com -Port (7000+$_) -WarningAction SilentlyContinue|Out-Null}; 'knock sequence sent'\"",
                    "Lab sequential port touches (port-knocking proxy).")],
    "T1568.001": [c("windows", "nslookup example.com & echo AF fast-flux proxy - single lab resolution",
                    "Lab DNS resolution (fast-flux proxy).")],
    "T1568.002": [c("windows", "powershell -NoProfile -Command \"$d=(Get-Date).DayOfYear; ('af{0}.example.com' -f $d)\"",
                    "Computes a date-seeded pseudo-domain string locally (DGA proxy; not resolved).")],
    "T1568.003": [c("windows", "powershell -NoProfile -Command \"[Convert]::ToInt64('0A000001',16)\"",
                    "Lab arithmetic on a hex string (DNS-calculation proxy).")],
    "T1572": [c("windows", "powershell -NoProfile -Command \"Test-NetConnection example.com -Port 443|Select TcpTestSucceeded\"",
                "Single lab TLS-port check (protocol-tunneling proxy; no tunnel established).")],
    "T1573.001": [c("windows", "powershell -NoProfile -Command \"$a=[Security.Cryptography.Aes]::Create(); $a.KeySize\"",
                    "Instantiates a symmetric cipher locally (symmetric-crypto C2 proxy).")],
    "T1573.002": [c("windows", "powershell -NoProfile -Command \"$r=[Security.Cryptography.RSA]::Create(2048); $r.KeySize\"",
                    "Instantiates an RSA key locally (asymmetric-crypto C2 proxy).")],
    "T1659": [c("windows", "powershell -NoProfile -Command \"(Invoke-WebRequest https://example.com -UseBasicParsing).StatusCode\"",
                "Lab fetch to an example host (content-injection proxy; nothing injected).")],
    "T1665": [c("windows", "nslookup example.com & echo AF hide-infrastructure proxy (read-only resolution)",
                "Lab resolution as a hide-infrastructure proxy.")],
}
