"""Extended lab commands — Part 1: Command & Control (application layer, proxy, encoding)."""
from .ext_helper import LOOPBACK_DNS, LOOPBACK_PING, c, loopback_tcp

PART = {
    "T1001": [c("windows", "powershell -NoProfile -Command \"-join('AdversaryFlow'.ToCharArray()|%{[int][char]$_})\"",
                "Lab data-obfuscation proxy (encodes a marker string locally).")],
    "T1001.001": [c("windows", "powershell -NoProfile -Command \"([byte[]](1..64|%{Get-Random -Max 255})).Length\"",
                    "Generates junk bytes locally (junk-data padding proxy; nothing sent).")],
    "T1001.002": [c("windows", "powershell -NoProfile -Command \"Add-Content $env:TEMP\\af_stego.txt 'AF marker'; (Get-Item $env:TEMP\\af_stego.txt).Length\"",
                    "Steganography proxy — hides a marker in a temp file.", "del %TEMP%\\af_stego.txt 2>nul")],
    "T1001.003": [loopback_tcp("Loopback-only protocol-impersonation proxy. Does not contact the public internet.")],
    "T1008": [c("windows", f"{LOOPBACK_DNS} & {LOOPBACK_DNS}",
                "Loopback DNS via the primary resolver twice (fallback-channel proxy).")],
    "T1071": [loopback_tcp("Loopback-only application-layer C2 proxy. Does not contact the public internet.")],
    "T1071.002": [c("windows", "powershell -NoProfile -Command \"'AdversaryFlow lab local transfer marker'\"",
                    "Local transfer marker. Does not download from the network.")],
    "T1071.003": [loopback_tcp("Loopback-only mail-protocol C2 proxy. No mail is sent.")],
    "T1071.004": [c("windows", "nslookup -type=TXT localhost",
                    "Loopback DNS TXT lookup (DNS C2 proxy).")],
    "T1090.001": [c("windows", "netsh interface portproxy show all & echo AF internal-proxy config read (read-only)",
                    "Read-only view of local port-proxy config.")],
    "T1090.002": [c("windows", "powershell -NoProfile -Command \"[Net.WebRequest]::DefaultWebProxy | Select Address\"",
                    "Reads the configured web proxy (read-only). Does not contact a remote host.")],
    "T1090.003": [c("windows", f"{LOOPBACK_DNS} & echo AF multi-hop-proxy proxy - single lab resolution only",
                    "Lab DNS lookup as a multi-hop-proxy bounded lab simulation.")],
    "T1090.004": [loopback_tcp("Loopback-only domain-fronting proxy. Does not contact the public internet.")],
    "T1092": [c("windows", "powershell -NoProfile -Command \"Get-Volume|? DriveType -eq 'Removable'|Select DriveLetter\"",
                "Enumerates removable media (removable-media C2 proxy; read-only).")],
    "T1095": [c("windows", LOOPBACK_PING,
                "Loopback ICMP echo (non-application-layer protocol C2 proxy).")],
    "T1102": [loopback_tcp("Loopback-only web-service C2 proxy. Does not contact the public internet.")],
    "T1102.001": [loopback_tcp("Loopback-only dead-drop-resolver proxy. Nothing is parsed as C2.")],
    "T1102.002": [loopback_tcp("Loopback-only bidirectional-comms proxy.")],
    "T1102.003": [loopback_tcp("Loopback-only one-way-comms proxy.")],
    "T1104": [c("windows", f"{LOOPBACK_DNS} & echo AdversaryFlow lab multi-stage channel",
                "Two lab staged loopback steps (multi-stage-channel proxy).")],
    "T1132": [c("windows", "powershell -NoProfile -Command \"[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('AdversaryFlow'))\"",
                "Base64-encodes a marker (data-encoding proxy).")],
    "T1132.001": [c("windows", "powershell -NoProfile -Command \"[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes('AF'))\"",
                    "Standard base64 encoding of a marker (standard-encoding proxy).")],
    "T1132.002": [c("windows", "powershell -NoProfile -Command \"(([Text.Encoding]::UTF8.GetBytes('AF'))|%{'{0:x2}' -f $_}) -join ''\"",
                    "Hex (non-standard) encoding of a marker (non-standard-encoding proxy).")],
    "T1205": [c("windows", f"{LOOPBACK_PING} & echo AF traffic-signaling proxy (single lab packet)",
                "Single loopback ping (traffic-signaling proxy).")],
    "T1205.001": [loopback_tcp("Loopback-only port-knocking proxy. Three touches stay on 127.0.0.1.")],
    "T1568.001": [c("windows", f"{LOOPBACK_DNS} & echo AF fast-flux proxy - single lab resolution",
                    "Loopback DNS resolution (fast-flux proxy).")],
    "T1568.002": [c("windows", "powershell -NoProfile -Command \"$d=(Get-Date).DayOfYear; ('af{0}.example.com' -f $d)\"",
                    "Computes a date-seeded pseudo-domain string locally (DGA proxy; not resolved).")],
    "T1568.003": [c("windows", "powershell -NoProfile -Command \"[Convert]::ToInt64('0A000001',16)\"",
                    "Lab arithmetic on a hex string (DNS-calculation proxy).")],
    "T1572": [loopback_tcp("Loopback-only protocol-tunneling proxy. No tunnel is established.")],
    "T1573.001": [c("windows", "powershell -NoProfile -Command \"$a=[Security.Cryptography.Aes]::Create(); $a.KeySize\"",
                    "Instantiates a symmetric cipher locally (symmetric-crypto C2 proxy).")],
    "T1573.002": [c("windows", "powershell -NoProfile -Command \"$r=[Security.Cryptography.RSA]::Create(2048); $r.KeySize\"",
                    "Instantiates an RSA key locally (asymmetric-crypto C2 proxy).")],
    "T1659": [loopback_tcp("Loopback-only content-injection proxy. Nothing is injected.")],
    "T1665": [c("windows", f"{LOOPBACK_DNS} & echo AF hide-infrastructure proxy (read-only resolution)",
                "Loopback resolution as a hide-infrastructure proxy.")],
}
