"""Extended lab commands — Part 11: Initial Access, Lateral Movement, misc Privilege Escalation."""
from .ext_helper import c

PART = {
    # ---- Initial Access ----
    "T1078.001": [c("windows", "net user Guest & echo AF default-accounts proxy (read-only)",
                    "Reads a default account (read-only; nothing used).")],
    "T1078.002": [c("windows", "net user %USERNAME% /domain 2>nul & echo AF domain-accounts proxy (read-only)",
                    "Reads the current domain account (read-only).")],
    "T1078.003": [c("windows", "net user %USERNAME% & echo AF local-accounts proxy (read-only)",
                    "Reads the current local account (read-only).")],
    "T1078.004": [c("cloud", "az account show -o table 2>nul || aws sts get-caller-identity 2>nul & echo AF cloud-accounts proxy (read-only)",
                    "Read-only cloud identity call (requires CLI auth).")],
    "T1091": [c("windows", "powershell -NoProfile -Command \"Get-Volume|? DriveType -eq 'Removable'|Select DriveLetter\"",
                "Enumerates removable media (replication-through-removable-media proxy; nothing written).")],
    "T1195": [c("windows", "cmd.exe /c \"echo AF supply-chain-compromise proxy - no software/dependency modified\"",
                "Bounded lab simulation only.")],
    "T1195.001": [c("windows", "cmd.exe /c \"echo AF compromise-software-dependencies proxy - no dependency modified\"",
                    "Bounded lab simulation only.")],
    "T1195.002": [c("windows", "cmd.exe /c \"echo AF compromise-software-supply-chain proxy - no build/artifact modified\"",
                    "Bounded lab simulation only.")],
    "T1199": [c("windows", "cmd.exe /c \"echo AF trusted-relationship proxy - no third-party trust abused\"",
                "Bounded lab simulation only.")],
    "T1200": [c("windows", "powershell -NoProfile -Command \"Get-PnpDevice -Class USB -EA SilentlyContinue|Select -First 5 FriendlyName\"",
                "Enumerates USB devices (hardware-additions proxy; read-only).")],
    "T1566": [c("windows", "cmd.exe /c \"echo AF phishing proxy - no email/message sent\"",
                "Bounded lab simulation only — no phishing message is sent.")],
    "T1566.003": [c("windows", "cmd.exe /c \"echo AF spearphishing-via-service proxy - no message sent\"",
                    "Bounded lab simulation only.")],
    "T1566.004": [c("windows", "cmd.exe /c \"echo AF spearphishing-voice proxy - no call placed\"",
                    "Bounded lab simulation only.")],
    "T1669": [c("windows", "netsh wlan show profiles & echo AF Wi-Fi-networks proxy (list saved profiles read-only)",
                "Lists saved Wi-Fi profiles (read-only).")],
    "T1671": [c("cloud", "cmd.exe /c \"echo AF cloud-application-integration proxy - no OAuth app/integration added\"",
                "Bounded lab simulation only.")],
    # ---- Lateral Movement ----
    "T1021": [c("windows", "net view /all 2>nul & echo AF remote-services proxy (enumerate only, no session opened)",
                "Enumerates remote systems (remote-services proxy; read-only).")],
    "T1021.004": [c("linux", "ssh -V 2>&1 & echo 'AF SSH proxy (client present, no connection made)'",
                    "Confirms the SSH client (proxy; no connection made)."),
                  c("windows", "where ssh.exe 2>nul & echo AF SSH proxy (client present, no connection made)")],
    "T1021.005": [c("windows", "powershell -NoProfile -Command \"Get-Service *vnc* -EA SilentlyContinue|Select Name,Status; 'VNC proxy (read-only)'\"",
                    "Enumerates VNC services (read-only).")],
    "T1021.007": [c("cloud", "az account show -o table 2>nul & echo AF cloud-services (lateral) proxy (read-only whoami)",
                    "Read-only cloud identity call (cloud-services lateral proxy).")],
    "T1080": [c("windows", "net share & echo AF taint-shared-content proxy (list shares read-only, nothing written)",
                "Lists shares (taint-shared-content proxy; nothing written).")],
    "T1210": [c("windows", "powershell -NoProfile -Command \"Test-NetConnection localhost -Port 445|Select TcpTestSucceeded\" & echo AF exploitation-of-remote-services proxy (lab port check, no exploit)",
                "Single lab local port check (exploitation-of-remote-services proxy; no exploit).")],
    "T1534": [c("windows", "cmd.exe /c \"echo AF internal-spearphishing proxy - no internal message sent\"",
                "Bounded lab simulation only.")],
    "T1563.002": [c("windows", "query session 2>nul & echo AF RDP-hijacking proxy (list sessions read-only, nothing hijacked)",
                    "Lists terminal sessions (read-only).")],
    # ---- Privilege Escalation (remaining) ----
    "T1068": [c("windows", "cmd.exe /c \"echo AF exploitation-for-privilege-escalation proxy - no exploit run\"",
                "Bounded lab simulation only — no exploit is executed.")],
    "T1611": [c("other", "cat /proc/1/cgroup 2>/dev/null | head & echo AF escape-to-host proxy (read cgroup only, no escape)",
                "Reads container cgroup info (escape-to-host proxy; read-only).")],
    # ---- misc ----
    "T1684": [c("windows", "cmd.exe /c \"echo AF social-engineering proxy - no target contacted\"",
                "Bounded lab simulation only.")],
    "T1684.001": [c("windows", "cmd.exe /c \"echo AF impersonation proxy - no identity impersonated\"",
                    "Bounded lab simulation only.")],
    "T1674": [c("windows", "cmd.exe /c \"echo AF input-injection proxy - no synthetic input generated\"",
                "Bounded lab simulation only.")],
    "T1569.003": [c("linux", "systemctl status --no-pager 2>/dev/null | head -3 & echo 'AF systemctl proxy (read-only status)'",
                    "Reads systemctl status (read-only).")],
    "T1578.002": [c("cloud", "az vm list -o table 2>nul & echo AF create-cloud-instance proxy (list only, nothing created)",
                    "Lists cloud instances (read-only; nothing created).")],
    "T1578.003": [c("cloud", "az vm list -o table 2>nul & echo AF delete-cloud-instance proxy (list only, nothing deleted)",
                    "Lists cloud instances (read-only; nothing deleted).")],
    "T1219": [c("windows", "powershell -NoProfile -Command \"Get-Service *AnyDesk*,*TeamViewer*,*ScreenConnect* -EA SilentlyContinue|Select Name,Status\"",
                "Enumerates remote-access-tool services (read-only).")],
    "T1219.001": [c("windows", "where code 2>nul & echo AF IDE-tunneling proxy (locate IDE only, no tunnel)",
                    "Locates the IDE (IDE-tunneling proxy; no tunnel).")],
    "T1219.002": [c("windows", "powershell -NoProfile -Command \"Get-Service *TeamViewer*,*AnyDesk* -EA SilentlyContinue|Select Name,Status\"",
                    "Enumerates remote-desktop software (read-only).")],
}
