const $=id=>document.getElementById(id);const values=()=>({actor:$('actor').value,target:$('target').value,objective:$('objective').value,platform:$('platform').value});
async function api(path,options={}){const r=await fetch(path,options),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}const json=(id,v)=>$(id).textContent=JSON.stringify(v,null,2);
async function refreshAll(){try{const [operator,provider]=await Promise.all([api('/api/operator-readiness'),api('/api/provider')]);json('readiness-output',{operator,provider})}catch(e){$('readiness-output').textContent=e.message}}
async function draft(provider){try{const body={...values(),fallback_offline:$('fallback').checked};const d=await api(provider?'/api/campaigns/provider':'/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});json('draft-output',d);campaigns()}catch(e){$('draft-output').textContent=e.message}}
async function campaigns(){try{const d=await api('/api/campaigns');$('campaign-list').innerHTML='<table><tr><th>Campaign</th><th>Status</th><th>Actions</th></tr>'+d.campaigns.map(c=>'<tr><td>'+c.campaign_id+'</td><td>'+c.status+'</td><td><button onclick="inspect(\''+c.campaign_id+'\')">Inspect</button></td></tr>').join('')+'</table>'}catch(e){$('campaign-output').textContent=e.message}}
async function inspect(id){try{const d=await api('/api/campaigns/'+encodeURIComponent(id));json('campaign-output',d);if(d.metadata.status==='awaiting-approval')$('campaign-output').insertAdjacentHTML('afterend','<p id="decision"><button onclick="approve(\''+id+'\')">Approve and run</button><button class="warn" onclick="decisionAction(\''+id+'\',\'reject\')">Reject</button><button class="warn" onclick="decisionAction(\''+id+'\',\'cancel\')">Cancel</button><button class="warn" onclick="reset(\''+id+'\')">Reset</button></p>')}catch(e){$('campaign-output').textContent=e.message}}
async function approve(id){const approver=prompt('Enter the RoE approver name:');const confirmation=prompt('Type APPROVE '+id);if(!approver||!confirmation)return;try{json('campaign-output',await api('/api/campaigns/'+id+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approver,confirmation})}));campaigns()}catch(e){$('campaign-output').textContent=e.message}}
async function decisionAction(id,action){const reason=prompt('Reason:');if(!reason)return;const body={reason};if(action==='reject')body.approver=prompt('RoE approver name:');try{json('campaign-output',await api('/api/campaigns/'+id+'/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));campaigns()}catch(e){$('campaign-output').textContent=e.message}}
async function reset(id){const confirmation=prompt('Type RESET '+id);if(!confirmation)return;try{json('campaign-output',await api('/api/campaigns/'+id+'/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation})}));campaigns()}catch(e){$('campaign-output').textContent=e.message}}
async function saveProfile(){try{json('provider-output',await api('/api/provider/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('profile').value,endpoint:$('endpoint').value,model:$('model').value,credential_env:$('credential').value})}));refreshAll()}catch(e){$('provider-output').textContent=e.message}}
async function profileAction(action){let body={name:$('profile').value};if(action==='remove'){body.confirmation=prompt('Type REMOVE '+body.name)||''}try{json('provider-output',await api('/api/provider/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));refreshAll()}catch(e){$('provider-output').textContent=e.message}}
async function providerTest(){if(!confirm('Send one harmless planning request?'))return;try{json('provider-output',await api('/api/provider/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values())}))}catch(e){$('provider-output').textContent=e.message}}
async function mitrePlan(){try{json('tools-output',await api('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values(),technique:$('technique').value})}))}catch(e){$('tools-output').textContent=e.message}}
async function support(){try{json('tools-output',await api('/api/support-bundle',{method:'POST'}))}catch(e){$('tools-output').textContent=e.message}}
async function demo(){try{json('tools-output',await api('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:$('actor').value,objective:$('objective').value,confirmation:$('demo-confirmation').value})}))}catch(e){$('tools-output').textContent=e.message}}
refreshAll();campaigns();
