const $=id=>document.getElementById(id);const values=()=>({actor:$('actor').value.trim(),target:$('target').value,objective:$('objective').value.trim(),platform:$('platform').value});const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,options),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}function outcome(id,title,detail,kind=''){const el=$(id);el.className='outcome '+kind;el.innerHTML='<strong>'+esc(title)+'</strong><br>'+esc(detail)}function explainError(id,error){outcome(id,'Nothing changed.',error.message+' Check the guidance above, correct the field named in the message, and try again.','bad')}
function finishSetup(){localStorage.setItem('adversaryflow-guided-setup','complete');$('first-run').hidden=true;refreshAll();$('readiness').scrollIntoView({behavior:'smooth'})}function next(title,detail,button='Check readiness',action=refreshAll){$('next-title').textContent=title;$('next-detail').textContent=detail;$('next-button').textContent=button;$('next-button').onclick=action}
function renderReadiness(doctor,provider){const checks=doctor.checks||[];$('readiness-output').innerHTML=checks.map(c=>'<div class="status '+(c.passed?'':'fail')+'"><strong>'+(c.passed?'Ready':'Needs attention')+'</strong><span>'+esc(c.name.replaceAll('-',' '))+'</span><small>'+esc(c.passed?c.detail:(c.remediation||c.detail))+'</small></div>').join('')+'<div class="status '+(provider.valid?'':'fail')+'"><strong>'+(provider.valid?'Ready':'Optional setup')+'</strong><span>Provider</span><small>'+esc(provider.valid?'Offline or approved provider is ready.':(provider.errors||[]).join(' '))+'</small></div>'}
async function refreshAll(){try{const [doctor,provider]=await Promise.all([api('/api/doctor',{method:'POST'}),api('/api/provider')]);renderReadiness(doctor,provider);if(doctor.passed)next('Create your first safe draft','Your local checks passed. Use the prefilled offline form; it does not run anything.','Create safe draft',()=>{$('actor').focus();$('actor').scrollIntoView({behavior:'smooth'})});else next('Fix local readiness first','One or more local checks need attention. Apply the safe fix, then refresh readiness.','Apply safe local fix',fixReadiness)}catch(e){explainError('readiness-output',e);next('We could not check readiness',e.message,'Try again',refreshAll)}}
async function fixReadiness(){try{const result=await api('/api/doctor/fix',{method:'POST'});outcome('readiness-output','Safe local fix complete.',result.fixes_applied.length?'Created: '+result.fixes_applied.join(', ')+'. Refreshing readiness…':'The safe local folders already existed. Refreshing readiness…');await refreshAll()}catch(e){explainError('readiness-output',e)}}
async function draft(provider){try{const body={...values(),fallback_offline:$('fallback').checked};const d=await api(provider?'/api/campaigns/provider':'/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});outcome('draft-output','Draft ready for review.',d.campaign_id+' was saved locally. Next, inspect its scope and selected safe abilities.');next('Review your saved draft','Inspect the campaign before any approval decision.','Review campaign',()=>inspect(d.campaign_id));campaigns()}catch(e){explainError('draft-output',e)}}
async function campaigns(){try{const d=await api('/api/campaigns');$('campaign-list').innerHTML=d.campaigns.length?'<table><tr><th>Campaign</th><th>Status</th><th>Next action</th></tr>'+d.campaigns.map(c=>'<tr><td>'+esc(c.campaign_id)+'</td><td>'+esc(c.status)+'</td><td><button onclick="inspect(\''+esc(c.campaign_id)+'\')">Inspect</button></td></tr>').join('')+'</table>':'<p class="muted">No saved campaigns yet. Create a safe offline draft to begin.</p>'}catch(e){explainError('campaign-output',e)}}
async function inspect(id){try{const d=await api('/api/campaigns/'+encodeURIComponent(id));const status=d.metadata.status;outcome('campaign-output','Campaign '+id, 'Status: '+status+'. '+(d.detail.next_action||'Review the details before proceeding.'));let actions='';if(status==='awaiting-approval')actions='<button onclick="approve(\''+esc(id)+'\')">Approve and run</button><button class="warn" onclick="decisionAction(\''+esc(id)+'\',\'reject\')">Reject</button><button class="warn" onclick="decisionAction(\''+esc(id)+'\',\'cancel\')">Cancel</button>';actions+='<button class="warn" onclick="reset(\''+esc(id)+'\')">Reset saved campaign</button>';$('campaign-output').insertAdjacentHTML('beforeend','<p>'+actions+'</p><details><summary>Show campaign details</summary><pre>'+esc(JSON.stringify(d,null,2))+'</pre></details>')}catch(e){explainError('campaign-output',e)}}
async function approve(id){if(!confirm('Approval starts only the built-in local synthetic emulation. Confirm the schedule and RoE scope before continuing.'))return;const approver=prompt('Enter the RoE approver name:');const confirmation=prompt('Type APPROVE '+id);if(!approver||!confirmation)return;try{await api('/api/campaigns/'+id+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approver,confirmation})});outcome('campaign-output','Campaign completed.','The local synthetic run and report are ready for review.');campaigns()}catch(e){explainError('campaign-output',e)}}
async function decisionAction(id,action){const word=action==='reject'?'Rejecting records that this draft will not run.':'Cancelling stops this incomplete draft.';if(!confirm(word+' You can inspect it afterward. Continue?'))return;const reason=prompt('Brief reason:');if(!reason)return;const body={reason};if(action==='reject')body.approver=prompt('RoE approver name:');try{await api('/api/campaigns/'+id+'/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});outcome('campaign-output','Campaign '+action+'ed.', 'The decision was recorded locally.');campaigns()}catch(e){explainError('campaign-output',e)}}
async function reset(id){if(!confirm('Reset permanently removes this saved campaign only. This cannot be undone. Continue?'))return;const confirmation=prompt('Type RESET '+id);if(!confirmation)return;try{await api('/api/campaigns/'+id+'/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation})});outcome('campaign-output','Campaign reset.','The saved draft was permanently removed.');campaigns()}catch(e){explainError('campaign-output',e)}}
async function saveProfile(){try{const d=await api('/api/provider/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('profile').value,endpoint:$('endpoint').value,model:$('model').value,credential_env:$('credential').value})});outcome('provider-output','Profile saved.',d.saved+' contains no credential. Activate and allow it before use.');refreshAll()}catch(e){explainError('provider-output',e)}}
async function profileAction(action){const name=$('profile').value.trim();let body={name};if(action==='remove'){if(!confirm('Removing a profile deletes its non-secret settings. Continue?'))return;body.confirmation=prompt('Type REMOVE '+name)||''}try{await api('/api/provider/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});outcome('provider-output','Provider settings updated.',action==='allow'?'The exact profile settings are now approved.':action==='use'?'The profile is active.': 'The profile was removed.');refreshAll()}catch(e){explainError('provider-output',e)}}
async function providerTest(){if(!confirm('This sends one harmless planning request to the active approved provider. It does not save, approve, or run a campaign. Continue?'))return;try{await api('/api/provider/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values())});outcome('provider-output','Provider test passed.','One planning request was validated; no campaign was saved or run.')}catch(e){explainError('provider-output',e)}}
async function mitrePlan(){try{const d=await api('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values(),technique:$('technique').value})});outcome('tools-output','Dry-run plan ready.',d.notice+' Review the plan; no campaign was created.')}catch(e){explainError('tools-output',e)}}
async function support(){try{const d=await api('/api/support-bundle',{method:'POST'});outcome('tools-output','Redacted support bundle created.',d.bundle+' contains local diagnostics to share with support.')}catch(e){explainError('tools-output',e)}}
async function demo(){if(!confirm('The demo runs only built-in local synthetic actions and creates a local report. It does not contact an external target. Continue?'))return;try{const d=await api('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:$('actor').value,objective:$('objective').value,confirmation:$('demo-confirmation').value})});outcome('tools-output','Safe demo complete.','Review the telemetry report in '+d.run_dir+'.');next('Learn from the report','Use the result to choose a focused objective for your next draft.','Create another draft',()=>{$('objective').focus();$('objective').scrollIntoView({behavior:'smooth'})})}catch(e){explainError('tools-output',e)}}
if(!localStorage.getItem('adversaryflow-guided-setup'))$('first-run').hidden=false;refreshAll();campaigns();
