const $=id=>document.getElementById(id);const values=()=>({actor:$('actor').value.trim(),target:$('target').value,objective:$('objective').value.trim(),platform:$('platform').value});const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,options),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}function outcome(id,title,detail,kind=''){const el=$(id);el.className='outcome '+kind;el.innerHTML='<strong>'+esc(title)+'</strong><br>'+esc(detail)}function explainError(id,error){outcome(id,'Nothing changed.',error.message+' Check the guidance above, correct the field named in the message, and try again.','bad');toast('Nothing changed',error.message,'bad')}
function finishSetup(){localStorage.setItem('adversaryflow-guided-setup','complete');$('first-run').hidden=true;refreshAll();$('readiness').scrollIntoView({behavior:'smooth'})}function next(title,detail,button='Check readiness',action=refreshAll){$('next-title').textContent=title;$('next-detail').textContent=detail;$('next-button').textContent=button;$('next-button').onclick=action}
function renderReadiness(doctor,provider){const checks=doctor.checks||[];$('readiness-output').innerHTML=checks.map(c=>'<div class="status '+(c.passed?'':'fail')+'"><strong>'+(c.passed?'Ready':'Needs attention')+'</strong><span>'+esc(c.name.replaceAll('-',' '))+'</span><small>'+esc(c.passed?c.detail:(c.remediation||c.detail))+'</small></div>').join('')+'<div class="status '+(provider.valid?'':'fail')+'"><strong>'+(provider.valid?'Ready':'Optional setup')+'</strong><span>Provider</span><small>'+esc(provider.valid?'Offline or approved provider is ready.':(provider.errors||[]).join(' '))+'</small></div>'}
async function refreshAll(){setHealthBadge('checking','Checking readiness…');try{const [doctor,provider]=await Promise.all([api('/api/doctor',{method:'POST'}),api('/api/provider')]);renderReadiness(doctor,provider);const failed=(doctor.checks||[]).filter(c=>!c.passed).length;setHealthBadge(doctor.passed?'good':'warn',doctor.passed?'Ready':failed+' check'+(failed===1?'':'s')+' need attention');if(doctor.passed)next('Create your first safe draft','Your local checks passed. Use the prefilled offline form; it does not run anything.','Create safe draft',()=>{$('actor').focus();$('actor').scrollIntoView({behavior:'smooth'})});else next('Fix local readiness first','One or more local checks need attention. Apply the safe fix, then refresh readiness.','Apply safe local fix',fixReadiness)}catch(e){setHealthBadge('bad','Readiness check failed');explainError('readiness-output',e);next('We could not check readiness',e.message,'Try again',refreshAll)}}
async function fixReadiness(){try{const result=await api('/api/doctor/fix',{method:'POST'});outcome('readiness-output','Safe local fix complete.',result.fixes_applied.length?'Created: '+result.fixes_applied.join(', ')+'. Refreshing readiness…':'The safe local folders already existed. Refreshing readiness…');toast('Safe fix applied',result.fixes_applied.length?'Created '+result.fixes_applied.length+' local folder(s).':'Local folders already existed.','good');await refreshAll()}catch(e){explainError('readiness-output',e)}}
async function draft(provider){try{const body={...values(),fallback_offline:$('fallback').checked};const d=await api(provider?'/api/campaigns/provider':'/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});outcome('draft-output','Draft ready for review.',d.campaign_id+' was saved locally. Next, inspect its scope and selected safe abilities.');toast('Draft saved',d.campaign_id+' is ready for review.','good');next('Review your saved draft','Inspect the campaign before any approval decision.','Review campaign',()=>inspect(d.campaign_id));campaigns()}catch(e){explainError('draft-output',e)}}
async function campaigns(){try{const d=await api('/api/campaigns');$('campaign-list').innerHTML=d.campaigns.length?'<table><tr><th>Campaign</th><th>Status</th><th>Next action</th></tr>'+d.campaigns.map(c=>'<tr><td>'+esc(c.campaign_id)+'</td><td>'+esc(c.status)+'</td><td><button onclick="inspect(\''+esc(c.campaign_id)+'\')">Inspect</button></td></tr>').join('')+'</table>':'<p class="muted">No saved campaigns yet. Create a safe offline draft to begin.</p>'}catch(e){explainError('campaign-output',e)}}
function pillList(items,empty){return (items&&items.length)?items.map(x=>'<span>'+esc(x)+'</span>').join(''):'<span class="muted">'+esc(empty||'none')+'</span>'}
function inspectDiff(x){const s=x.scope||{},abilities=x.abilities||[];const abil=abilities.length?abilities.map(a=>'<div style="margin-bottom:8px"><strong>'+esc(a.name||a.id)+'</strong> <span class="muted">'+esc(a.technique_id||'')+' · '+esc(a.network_scope||'')+'</span><div class="tel"><span>'+esc(a.telemetry_count)+' expected telemetry signals</span></div></div>').join(''):'<span class="muted">No reviewed abilities selected.</span>';const integ=x.integrity||{},color=integ.status==='verified'?'good':integ.status==='review-required'?'bad':'warn';return '<div class="inspect-grid">'+
'<div class="box"><h4>Scope</h4><p><strong>Target:</strong> '+esc(s.target)+'<br><strong>Objective:</strong> '+esc(s.objective)+'<br><strong>Risk:</strong> '+esc(s.risk_level)+'</p></div>'+
'<div class="box"><h4>Integrity</h4><p class="'+color+'" style="color:var(--'+color+')"><strong>'+esc(String(integ.status||'unknown').replace(/-/g,' '))+'</strong></p><p class="muted">'+esc(integ.detail||'')+'</p></div>'+
'<div class="box"><h4>Abilities &amp; telemetry</h4>'+abil+'</div>'+
'<div class="box"><h4>Stop conditions</h4><div class="tel">'+pillList(x.stop_conditions,'No stop conditions recorded')+'</div></div>'+
'</div>'+
(x.approval_readiness?'<div class="box" style="margin-top:12px"><h4>Approval readiness</h4><ul style="margin:0;padding-left:18px">'+(x.approval_readiness.checks||[]).map(c=>'<li>'+(c.passed?'✓ ':'✗ ')+esc(c.label)+'</li>').join('')+'</ul><p class="muted">'+esc(x.approval_readiness.next||'')+'</p></div>':'')+
(x.terminal_next?'<p class="muted" style="margin-top:12px">'+esc(x.terminal_next.label)+':</p><div class="cmd"><code id="inspect-cmd">'+esc(x.terminal_next.command)+'</code><button class="copy-btn" onclick="copyText(document.getElementById(\'inspect-cmd\').textContent,this)">Copy</button></div><p class="muted">'+esc(x.terminal_next.detail||'')+'</p>':'')+
'<p class="offline-note">This review is read-only. Inspecting, approving in the browser, or copying a command never contacts an external target — execution stays local synthetic simulation.</p>';}
async function inspect(id){try{const d=await api('/api/campaigns/'+encodeURIComponent(id));const status=d.metadata.status;outcome('campaign-output','Campaign '+id, 'Status: '+status+'. '+(d.detail.next_action||'Review the details before proceeding.'));let actions='';if(status==='awaiting-approval')actions='<button onclick="approve(\''+esc(id)+'\')">Approve and run</button><button class="warn" onclick="decisionAction(\''+esc(id)+'\',\'reject\')">Reject</button><button class="warn" onclick="decisionAction(\''+esc(id)+'\',\'cancel\')">Cancel</button>';actions+='<button class="warn" onclick="reset(\''+esc(id)+'\')">Reset saved campaign</button>';$('campaign-output').insertAdjacentHTML('beforeend','<p>'+actions+'</p>'+inspectDiff(d.detail||{})+'<details><summary>Show raw campaign record</summary><pre>'+esc(JSON.stringify(d,null,2))+'</pre></details>')}catch(e){explainError('campaign-output',e)}}
async function approve(id){if(!confirm('Approval starts only the built-in local synthetic emulation. Confirm the schedule and RoE scope before continuing.'))return;const approver=prompt('Enter the RoE approver name:');const confirmation=prompt('Type APPROVE '+id);if(!approver||!confirmation)return;try{await api('/api/campaigns/'+id+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approver,confirmation})});outcome('campaign-output','Campaign completed.','The local synthetic run and report are ready for review.');toast('Campaign completed',id+' ran locally; report is ready.','good');campaigns()}catch(e){explainError('campaign-output',e)}}
async function decisionAction(id,action){const word=action==='reject'?'Rejecting records that this draft will not run.':'Cancelling stops this incomplete draft.';if(!confirm(word+' You can inspect it afterward. Continue?'))return;const reason=prompt('Brief reason:');if(!reason)return;const body={reason};if(action==='reject')body.approver=prompt('RoE approver name:');try{await api('/api/campaigns/'+id+'/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});outcome('campaign-output','Campaign '+action+'ed.', 'The decision was recorded locally.');campaigns()}catch(e){explainError('campaign-output',e)}}
async function reset(id){if(!confirm('Reset permanently removes this saved campaign only. This cannot be undone. Continue?'))return;const confirmation=prompt('Type RESET '+id);if(!confirmation)return;try{await api('/api/campaigns/'+id+'/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation})});outcome('campaign-output','Campaign reset.','The saved draft was permanently removed.');campaigns()}catch(e){explainError('campaign-output',e)}}
async function saveProfile(){try{const d=await api('/api/provider/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('profile').value,endpoint:$('endpoint').value,model:$('model').value,credential_env:$('credential').value})});outcome('provider-output','Profile saved.',d.saved+' contains no credential. Activate and allow it before use.');refreshAll()}catch(e){explainError('provider-output',e)}}
async function profileAction(action){const name=$('profile').value.trim();let body={name};if(action==='remove'){if(!confirm('Removing a profile deletes its non-secret settings. Continue?'))return;body.confirmation=prompt('Type REMOVE '+name)||''}try{await api('/api/provider/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});outcome('provider-output','Provider settings updated.',action==='allow'?'The exact profile settings are now approved.':action==='use'?'The profile is active.': 'The profile was removed.');refreshAll()}catch(e){explainError('provider-output',e)}}
async function providerTest(){if(!confirm('This sends one harmless planning request to the active approved provider. It does not save, approve, or run a campaign. Continue?'))return;try{await api('/api/provider/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values())});outcome('provider-output','Provider test passed.','One planning request was validated; no campaign was saved or run.')}catch(e){explainError('provider-output',e)}}
async function mitrePlan(){try{const d=await api('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values(),technique:$('technique').value})});outcome('tools-output','Dry-run plan ready.',d.notice+' Review the plan; no campaign was created.')}catch(e){explainError('tools-output',e)}}
async function support(){try{const d=await api('/api/support-bundle',{method:'POST'});outcome('tools-output','Redacted support bundle created.',d.bundle+' contains local diagnostics to share with support.')}catch(e){explainError('tools-output',e)}}
async function demo(){if(!confirm('The demo runs only built-in local synthetic actions and creates a local report. It does not contact an external target. Continue?'))return;try{const d=await api('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:$('actor').value,objective:$('objective').value,confirmation:$('demo-confirmation').value})});outcome('tools-output','Safe demo complete.','Review the telemetry report in '+d.run_dir+'.');next('Learn from the report','Use the result to choose a focused objective for your next draft.','Create another draft',()=>{$('objective').focus();$('objective').scrollIntoView({behavior:'smooth'})})}catch(e){explainError('tools-output',e)}}
let archiveRows=[],archiveSort={key:'campaign_id',dir:1},archiveTimer=null;
function archiveSearchDebounced(){clearTimeout(archiveTimer);archiveTimer=setTimeout(archiveSearch,250)}
function sortArchive(key){if(archiveSort.key===key)archiveSort.dir*=-1;else archiveSort={key,dir:1};renderArchive()}
function renderArchive(){const out=$('archive-output'),count=$('archive-count');if(!archiveRows.length){count.textContent='';out.textContent='No local campaigns matched your search.';return}const k=archiveSort.key,dir=archiveSort.dir;const rows=[...archiveRows].sort((a,b)=>{const va=String((k==='tags'?(a.tags||[]).join(','):a[k])??'').toLowerCase(),vb=String((k==='tags'?(b.tags||[]).join(','):b[k])??'').toLowerCase();return va<vb?-dir:va>vb?dir:0});const arrow=key=>'sortable'+(archiveSort.key===key?(dir>0?' asc':' desc'):'');count.textContent=archiveRows.length+' campaign'+(archiveRows.length===1?'':'s')+' matched.';out.innerHTML='<strong>Local archive results</strong><table><tr><th class="'+arrow('campaign_id')+'" onclick="sortArchive(\'campaign_id\')">Campaign</th><th class="'+arrow('owner')+'" onclick="sortArchive(\'owner\')">Ownership</th><th class="'+arrow('tags')+'" onclick="sortArchive(\'tags\')">Tags</th><th>Actions</th></tr>'+rows.map(c=>'<tr><td>'+esc(c.campaign_id)+'<br><small>'+esc(c.objective)+'</small></td><td>'+esc(c.owner||'unassigned')+'<br><small>'+esc(c.retention_days?c.retention_days+' day retention':'retention not set')+'</small></td><td>'+esc((c.tags||[]).join(', ')||'none')+'</td><td><button onclick="exportSummary(\''+esc(c.campaign_id)+'\')">Export summary</button><button class="secondary" onclick="tagCampaign(\''+esc(c.campaign_id)+'\')">Edit tags</button><button class="secondary" onclick="archiveControls(\''+esc(c.campaign_id)+'\')">Owner & retention</button></td></tr>').join('')+'</table>'}
async function archiveSearch(){try{const q=$('archive-query').value.trim(),tag=($('archive-tag')?$('archive-tag').value.trim():'');const d=await api('/api/archive?q='+encodeURIComponent(q)+'&tag='+encodeURIComponent(tag));archiveRows=d.campaigns||[];renderArchive()}catch(e){explainError('archive-output',e)}}
async function tagCampaign(id){const raw=prompt('Tags, separated by commas (lowercase letters, numbers, hyphens, underscores):');if(raw===null)return;try{const d=await api('/api/archive/tags',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaign_id:id,tags:raw.split(',').map(v=>v.trim()).filter(Boolean)})});outcome('archive-output','Tags saved.',id+' is tagged: '+(d.tags.join(', ')||'none')+'.');archiveSearch()}catch(e){explainError('archive-output',e)}}
async function archiveControls(id){const owner=prompt('Campaign owner (name or team):');if(!owner)return;const raw=prompt('Retention days (1 to 3650):','365');if(raw===null)return;const retention_days=Number(raw);try{const d=await api('/api/archive/controls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaign_id:id,owner,retention_days})});outcome('archive-output','Archive controls saved.',id+' is owned by '+d.owner+' with '+d.retention_days+' days retention.');archiveSearch()}catch(e){explainError('archive-output',e)}}
async function exportSummary(id){try{const d=await api('/api/exports/executive-summary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaign_id:id})});outcome('archive-output','Stakeholder summary exported.','Markdown: '+d.markdown+' PDF: '+d.pdf)}catch(e){explainError('archive-output',e)}}
async function providerCompatibility(){try{const d=await api('/api/provider/compatibility');$('compatibility-output').innerHTML='<strong>'+(d.ready?'Ready for one harmless test.':'Setup needed before a request.')+'</strong><ul>'+d.checks.map(c=>'<li>'+(c.passed?'Ready: ':'Needs attention: ')+esc(c.label)+'</li>').join('')+'</ul><span>'+esc(d.next)+'</span>'}catch(e){explainError('compatibility-output',e)}}
async function learnTechnique(){try{const d=await api('/api/learning?technique='+encodeURIComponent($('technique').value));$('learning-output').innerHTML=d.abilities.length?'<strong>'+esc(d.technique)+'</strong><p>'+esc(d.boundary)+'</p>'+d.abilities.map(a=>'<details open><summary>'+esc(a.name)+' ('+esc(a.technique_id)+')</summary><p><strong>Safe simulation:</strong> '+esc(a.simulation_action)+'</p><p><strong>Expected telemetry:</strong> '+esc(a.expected_telemetry.join('; '))+'</p><p><strong>How to interpret:</strong> '+esc(a.interpretation)+'</p></details>').join(''):'No reviewed local ability matches this technique. Choose a technique used by the safe catalog.'}catch(e){explainError('learning-output',e)}}
async function detectionMappings(){try{const d=await api('/api/detection-mappings?technique='+encodeURIComponent($('technique').value));$('learning-output').innerHTML=d.mappings.length?'<strong>Detection-rule guidance</strong><p>'+esc(d.notice)+'</p>'+d.mappings.map(m=>'<details open><summary>'+esc(m.ability)+' ('+esc(m.technique_id)+')</summary><p><strong>Telemetry to map:</strong> '+esc(m.telemetry.join('; '))+'</p><p><strong>Recommendation:</strong> '+esc(m.recommendation)+'</p><p><strong>Useful formats:</strong> '+esc(m.rule_formats.join(', '))+'</p></details>').join(''):'No reviewed local mapping matches this technique.'}catch(e){explainError('learning-output',e)}}
async function coverageDashboard(){try{const d=await api('/api/coverage'),s=d.summary;$('coverage-output').innerHTML='<strong>'+s.campaigns+' campaigns · '+s.techniques+' techniques · '+s.detections+' detections · '+s.gaps+' gaps</strong><table><tr><th>Technique</th><th>Execution</th><th>Telemetry</th><th>Detection</th><th>Gaps</th></tr>'+d.techniques.map(t=>'<tr><td>'+esc(t.technique_id)+'</td><td>'+t.behavior_succeeded+'/'+t.executions+'</td><td>'+t.telemetry_observed+'/'+t.executions+'</td><td>'+t.detections+'</td><td>'+t.gaps+'</td></tr>').join('')+'</table><small>Flow: '+esc(d.flow.join(' → '))+'</small>'}catch(e){explainError('coverage-output',e)}}
async function loadRoeEditor(){try{const d=await api('/api/roe');$('roe-json').value=JSON.stringify(d.roe,null,2);outcome('roe-output','RoE loaded.',d.history.length?'Recent local history entries: '+d.history.length+'.':'No prior local RoE edits recorded.')}catch(e){explainError('roe-output',e)}}
async function saveRoeEditor(){if(!confirm('Saving replaces the active local RoE after validation and records a dated history snapshot. Campaigns created under a previous RoE may need review. Continue?'))return;try{const data=JSON.parse($('roe-json').value);data.editor=$('roe-editor').value;const d=await api('/api/roe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});outcome('roe-output','RoE saved and versioned.','Saved by '+d.history_entry.editor+'. Previous version: '+d.history_entry.previous);refreshAll()}catch(e){explainError('roe-output',e)}}
let ctidBundle='';async function createCtidFixtureBundle(){if(!confirm('This creates local, benign JSONL fixtures only. Use them exclusively through an approved lab replay or test-ingestion path. Continue?'))return;try{const d=await api('/api/ctid-fixtures',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({retest_of:ctidBundle||null})});ctidBundle=d.bundle;outcome('ctid-output','Fixture bundle created.',d.next+' Bundle: '+d.bundle);$('ctid-fixtures').innerHTML='<p><strong>After approved lab replay, mark the detections that appeared:</strong></p>'+d.fixtures.map(f=>'<label class="check"><input type="checkbox" value="'+esc(f.id)+'"> '+esc(f.name)+' - '+esc(f.source)+' - '+esc(f.technique_id)+'</label>').join('')+'<button onclick="assessCtidFixtures()">Measure observed detections and write gap report</button>'}catch(e){explainError('ctid-output',e)}}
async function assessCtidFixtures(){if(!ctidBundle)return;const observed=[...$('ctid-fixtures').querySelectorAll('input:checked')].map(input=>input.value);try{const d=await api('/api/ctid-fixtures/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bundle:ctidBundle,observed_fixture_ids:observed})});outcome('ctid-output','Fixture evidence assessed.',d.observed_fixture_count+' of '+d.expected_fixture_count+' expected detections were recorded; '+d.detection_gap_count+' gaps need rule or control follow-up. A local training timeline and gap report were saved.')}catch(e){explainError('ctid-output',e)}}
const csv=id=>$(id).value.split(',').map(value=>value.trim()).filter(Boolean);let actorLastRun='';async function loadActorFixtureChoices(){try{const [fixtures,procedures]=await Promise.all([api('/api/ctid-fixtures'),api('/api/benign-procedures')]);$('actor-profile-fixtures').innerHTML='<p><strong>Approved benign fixtures</strong></p>'+fixtures.fixtures.map(f=>'<label class="check"><input type="checkbox" value="'+esc(f.id)+'" checked> '+esc(f.name)+' - '+esc(f.technique_id)+' - '+esc(f.source)+'</label>').join('');$('actor-profile-procedures').innerHTML='<p><strong>Approved local procedures</strong></p>'+procedures.procedures.map(p=>'<label class="check"><input type="checkbox" value="'+esc(p.id)+'"> '+esc(p.name)+' - '+esc(p.technique_id)+'<br><span class="hint">'+esc(p.action)+'</span></label>').join('')}catch(e){explainError('actor-profile-output',e)}}
async function saveActorProfile(){const fixture_ids=[...$('actor-profile-fixtures').querySelectorAll('input:checked')].map(input=>input.value),procedure_ids=[...$('actor-profile-procedures').querySelectorAll('input:checked')].map(input=>input.value);try{const d=await api('/api/actor-profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('actor-profile-name').value.trim(),actor:$('actor-profile-actor').value.trim(),aliases:csv('actor-profile-aliases'),sources:csv('actor-profile-sources'),technique_ids:csv('actor-profile-techniques'),fixture_ids,procedure_ids})});outcome('actor-profile-output','Actor validation profile saved.',d.actor+' now has '+d.fixture_ids.length+' fixtures and '+d.procedure_ids.length+' fixed benign procedures across the validation and retest workflow.');loadActorProfiles()}catch(e){explainError('actor-profile-output',e)}}
async function loadActorProfiles(){try{const d=await api('/api/actor-profiles');$('actor-profile-output').innerHTML=d.profiles.length?'<strong>Saved local profiles</strong><table><tr><th>Actor</th><th>Coverage</th><th>Actions</th></tr>'+d.profiles.map(p=>'<tr><td>'+esc(p.actor)+'<br><small>'+esc(p.name)+'</small></td><td>'+esc(p.technique_ids.join(', '))+'<br><small>'+p.fixture_ids.length+' fixtures, '+(p.procedure_ids||[]).length+' procedures</small></td><td><button onclick="planActorProfile(\''+esc(p.name)+'\')">Review plan</button><button class="secondary" onclick="runActorProfile(\''+esc(p.name)+'\')">Run safe validation</button></td></tr>').join('')+'</table>':'No actor validation profiles saved yet.'}catch(e){explainError('actor-profile-output',e)}}
async function planActorProfile(name){try{const d=await api('/api/actor-profiles/'+encodeURIComponent(name)+'/plan');outcome('actor-profile-output','Profile plan ready.',d.profile.actor+' covers '+d.coverage.length+' benign fixture validations. Next: create the local bundle, use your approved lab replay path, assess evidence, and retest gaps.')}catch(e){explainError('actor-profile-output',e)}}
async function runActorProfile(name){if(!confirm('This runs only selected fixed local benign procedures and/or creates local fixtures. It does not execute actor behavior, accept commands, or contact a target. Continue?'))return;try{const d=await api('/api/actor-profiles/'+encodeURIComponent(name)+'/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({retest_of:actorLastRun||null})});actorLastRun=(d.procedures||d.fixtures).run_id;outcome('actor-profile-output','Safe actor validation run created.',actorLastRun+' contains only the selected run-owned procedures and fixtures. Review evidence, assess detections, clean run-owned artifacts, then use the next run as a retest.')}catch(e){explainError('actor-profile-output',e)}}
// --- UX helpers: toasts, health badge, theme, copy, keyboard navigation ---
function toast(title,detail,kind=''){const c=$('toasts');if(!c)return;const el=document.createElement('div');el.className='toast '+kind;el.innerHTML='<strong>'+esc(title)+'</strong>'+(detail?esc(detail):'');c.appendChild(el);setTimeout(()=>{el.style.transition='opacity .3s';el.style.opacity='0';setTimeout(()=>el.remove(),300)},4200)}
function setHealthBadge(state,text){const b=$('health-badge');if(!b)return;b.className='badge '+state;const t=$('health-badge-text');if(t)t.textContent=text}
function fallbackCopy(text){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch(e){}ta.remove();return ok}
function copyFeedback(btn){if(btn){const o=btn.textContent;btn.textContent='Copied';btn.classList.add('copied');setTimeout(()=>{btn.textContent=o;btn.classList.remove('copied')},1500)}toast('Copied','Command copied to clipboard.','good')}
function copyText(text,btn){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(()=>copyFeedback(btn)).catch(()=>{if(fallbackCopy(text))copyFeedback(btn);else toast('Copy failed','Select the command and copy it manually.','bad')})}else if(fallbackCopy(text)){copyFeedback(btn)}else{toast('Copy failed','Select the command and copy it manually.','bad')}}
function decorateCopyBlocks(){document.querySelectorAll('code').forEach(el=>{if(!/adversaryflow/.test(el.textContent||'')||el.dataset.copyReady)return;el.dataset.copyReady='1';el.style.cursor='pointer';el.title='Click to copy this command';el.addEventListener('click',()=>copyText(el.textContent,null))})}
const THEME_LABELS={light:'☀️ Light',dark:'🌙 Dark',system:'🌗 System'};
function applyTheme(mode){const root=document.documentElement;if(mode==='light'||mode==='dark')root.setAttribute('data-theme',mode);else root.removeAttribute('data-theme');const btn=$('theme-toggle');if(btn)btn.textContent=THEME_LABELS[mode]||THEME_LABELS.system}
function currentTheme(){return localStorage.getItem('adversaryflow-theme')||'system'}
function setTheme(mode){localStorage.setItem('adversaryflow-theme',mode);applyTheme(mode)}
function cycleTheme(){const order=['system','light','dark'],next=order[(order.indexOf(currentTheme())+1)%order.length];setTheme(next);toast('Theme',{system:'Following your system setting.',light:'Light theme enabled.',dark:'Dark theme enabled.'}[next],'good')}
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey)return;const tgt=e.target;if(tgt&&typeof tgt.matches==='function'&&tgt.matches('input,textarea,select,[contenteditable]'))return;if(e.key==='t'||e.key==='T'){cycleTheme();return}if(/^[1-9]$/.test(e.key)){const cards=document.querySelectorAll('main section.card'),card=cards[+e.key-1];if(card){card.scrollIntoView({behavior:'smooth',block:'start'});const h=card.querySelector('h2');if(h){h.setAttribute('tabindex','-1');h.focus({preventScroll:true})}}}});
function updateDraftCli(){const el=$('draft-cli');if(!el)return;const v=values(),q=s=>String(s||'').replace(/"/g,'');let cmd='adversaryflow campaign --actor "'+q(v.actor)+'" --target "'+q(v.target)+'" --objective "'+q(v.objective)+'"';if($('fallback')&&$('fallback').checked)cmd+=' --fallback-offline';el.textContent=cmd}
['actor','objective','platform','target','fallback'].forEach(id=>{const el=$(id);if(el)el.addEventListener('input',updateDraftCli)});
applyTheme(currentTheme());decorateCopyBlocks();updateDraftCli();
if(!localStorage.getItem('adversaryflow-guided-setup'))$('first-run').hidden=false;refreshAll();campaigns();coverageDashboard();loadActorFixtureChoices();
